import { SwitchState } from "./types/itemTypes";

export const ROOM_NAME_TOKEN_START = "[[ROOM_NAME]]";
export const ROOM_NAME_TOKEN_END = "[[/ROOM_NAME]]";

export const OPENING_SPLASH = `You dream of falling.\n\n
The sensation of a bump, then a flip, then, for a moment, weightlessness. It's an almost peaceful sensation, for as long as it lasts, a flash of terror followed by an all too brief feeling of resignation, release, and finally, relief.\n\n
A second later you jolt awake on your back, naked, and gasping for air. The floor is cold and hard beneath you, smooth tile covered in a thin layer of grit, and the stale air is cool, causing your bare skin to prickle.\n\n
Still dazed, you stand up and put one hand against the wall until you're steady. You try to remember what happened, how you got here, and where here even is, but your mind is in a fog. You remember that you were in the middle of something, something important, but you must have really hit your head because everything is fragmented and at the moment, you can't even remember your own name.\n\n
You look yourself over. You have no idea why you're nude, but there isn't so much as a scratch or a bruise on you at least, and while you don't seem to be in any sort of immediate danger something in your mind is sounding the alarm.\n\nThere's something you need to be doing, and you're running out of time...`;

export const POWER_SECTION_MAP: Record<
  string,
  { section: string; activeWhen: SwitchState }
> = {
  TPADPOWER1: { section: "teleport-pads-green", activeWhen: "on" },
  TPADPOWER2: { section: "teleport-pads-white", activeWhen: "on" },
  TPADPOWER3: { section: "teleport-pads-blue", activeWhen: "on" },
  TPADPOWER4: { section: "teleport-pads-yellow", activeWhen: "on" },
  TPADPOWER5: { section: "teleport-pads-violet", activeWhen: "on" },
  TPADPOWER6: { section: "teleport-pads-maroon", activeWhen: "on" },
  Lvl1Lights: { section: "lights-level-one", activeWhen: "on" },
  Lvl2Lights: { section: "lights-level-two", activeWhen: "on" },
  Lvl3Lights: { section: "lights-level-three", activeWhen: "on" },
  Lvl4Lights: { section: "lights-level-four", activeWhen: "on" },
  Lvl5Lights: { section: "lights-level-five", activeWhen: "on" },
  Lvl6Lights: { section: "lights-level-six", activeWhen: "on" },
  Lvl7Lights: { section: "lights-level-seven", activeWhen: "on" },
  Lvl1Grav: { section: "gravity-level-one", activeWhen: "on" },
  Lvl2Grav: { section: "gravity-level-two", activeWhen: "on" },
  Lvl3Grav: { section: "gravity-level-three", activeWhen: "on" },
  Lvl4Grav: { section: "gravity-level-four", activeWhen: "on" },
  Lvl5Grav: { section: "gravity-level-five", activeWhen: "on" },
  Lvl6Grav: { section: "gravity-level-six", activeWhen: "on" },
  Lvl7Grav: { section: "gravity-level-seven", activeWhen: "on" },
  Lvl3Terminal: { section: "library-power", activeWhen: "on" },
  ParkSecurity: { section: "park-security", activeWhen: "on" },
  Lvl1Weapons: { section: "weapons-system", activeWhen: "on" },
  ECore: { section: "engine-room-power-lock", activeWhen: "on" },
  LoadDockDoor: { section: "loading-dock-door", activeWhen: "on" },
  LoadGrid: { section: "loading-grid", activeWhen: "on" },
  CryoLabs: { section: "cryo-labs", activeWhen: "on" },
  Sleepers: { section: "cryo-sleep", activeWhen: "on" },
};

export const playerScoreMap = {
  accessed_above_quad: { value: 5 },
  accessed_bridge: { value: 5 },
  accessed_engine_room: { value: 5 },
  accessed_hydroponics: { value: 5 },
  accessed_medical_lab: { value: 5 },
  accessed_medical_storage: { value: 5 },
  accessed_power_grid: { value: 5 },
  accessed_roof: { value: 5 },
  accessed_shuttle: { value: 5 },
  accessed_stasis_floor: { value: 5 },
  accessed_xenolab: { value: 5 },
  accessed_zoo_two: { value: 5 },
  activated_level_five_lights: { value: 5 },
  activated_level_two_lights: { value: 5 },
  activated_main_power: { value: 5 },
  activated_movie_projector: { value: 5 },
  activated_comet_link: { value: 5 },
  completed_engine_shut_down: { value: 5 },
  defeated_xl999: { value: 5 },
  discovered_magic_word: { value: 5 },
  found_elephant_lamp: { value: 5 },
  found_i_quit_note: { value: 5 },
  found_squirrel_cache: { value: 5 },
  gorilla_in_cryopod: { value: 5 },
  gorilla_sedated: { value: 5 },
  initiated_shutdown_from_terminal: { value: 5 },
  obtained_blue_badge: { value: 5 },
  obtained_violet_badge: { value: 5 },
  obtained_code_from_parrot: { value: 5 },
  obtained_coord_finder: { value: 5 },
  obtained_correct_thumb: { value: 5 },
  obtained_dogtag: { value: 5 },
  obtained_doll_key: { value: 5 },
  obtained_emp: { value: 5 },
  obtained_engine_room_key: { value: 5 },
  obtained_engine_shutdown_code: { value: 5 },
  obtained_gravity_boots: { value: 5 },
  obtained_green_badge: { value: 5 },
  obtained_maroon_badge: { value: 5 },
  obtained_park_pass: { value: 5 },
  obtained_infection_report: { value: 5 },
  obtained_innoculant: { value: 5 },
  obtained_lotto_ticket: { value: 5 },
  obtained_music_box: { value: 5 },
  obtained_new_z4_detonator: { value: 5 },
  obtained_nv_goggles: { value: 5 },
  obtained_orange_badge: { value: 5 },
  obtained_inframaroon_badge: { value: 5 },
  obtained_power_key: { value: 5 },
  obtained_radiation_cure: { value: 5 },
  obtained_secret_phone_number_1: { value: 5 },
  obtained_specimen_report: { value: 5 },
  obtained_ultraviolet_badge: { value: 5 },
  obtained_white_badge: { value: 5 },
  obtained_yellow_badge: { value: 5 },
  obtained_z4: { value: 5 },
  opened_safe: { value: 5 },
  rehydrated_slug: { value: 5 },
  saved_by_inertial_dampener: { value: 5 },
  saved_by_zap_protection: { value: 5 },
  solved_airlock_puzzle: { value: 5 },
  solved_blocked_engineering_puzzle: { value: 5 },
  solved_bloodbag_puzzle: { value: 5 },
  solved_cameragun_puzzle: { value: 5 },
  solved_flaregun_puzzle: { value: 5 },
  solved_hydroponics_fire_puzzle: { value: 5 },
  solved_mindgun_puzzle: { value: 5 },
  solved_slug_puzzle: { value: 5 },
  solved_spa_puzzle: { value: 5 },
  solved_stasis_gun_puzzle: { value: 5 },
  solved_z4_puzzle: { value: 5 },
  viewed_ship_log: { value: 5 },
} as const;

export const playerMemoryMap = {
  own_name: { value: 5 },
  own_image: { value: 5 },
  own_occupation: { value: 5 },
  own_voice: { value: 5 },
  own_handwriting: { value: 5 },
  aware_of_reincarnation: { value: 5 },
  aware_of_reincarnation_nature: { value: 5 },
  aware_of_own_role_in_reincarnation: { value: 5 },
  pinhole_cause: { value: 5 },
  aware_of_statue_nature: { value: 5 },
  aware_of_innoculant: { value: 5 },
  listened_to_music_box: { value: 5 },
  seen_self: { value: 0 },
  found_own_quarters: { value: 5 },
};
