export const INITIAL_CONTAINER_CONTENTS: Record<string, string[]> = {
  ThreeWestGimOneEndTable: ["GimOneJournal", "MensLockerKey2"],
  ThreeWestGimTwoEndTable: ["GimTwoJournal", "MensLockerKey9"],
  ThreeWestGimThreeEndTable: ["GimThreeJournal", "MensLockerKey11", "ParkPass"],
  ThreeWestCloset: [
    "GimOneShirt",
    "GimOnePants",
    "GimOneShoes",
    "GimTwoShirt",
    "GimTwoPants",
    "GimTwoShoes",
    "GimThreeShirt",
    "GimThreePants",
    "GimThreeShoes",
  ],
  SixEastMedicineChest: ["hornychew", "PheromonePerfume"],
  SixEastBedEndTable: ["OncheJournal"],
  SixEastBedDresser: [],
  SixEastCloset: [],
  IggyCollar: ["OncheSecurityRec"],
  DRUGTIN: ["GroovyCart"],
  SixWestMedicineChest: ["DRUGTIN"],
  SixWestWetBar: ["SixWestBourbon", "SixWestScotch", "SixWestBeer"],
  SixWestWineRack: ["SixWestWine1", "SixWestWine2", "SixWestWine3"],
  OneEastCloset: ["warren_tank_top", "warren_blue_jeans", "warren_tshirt"],
  TwoEastCloset: [
    "briggs_boots",
    "briggs_black_tshirt",
    "briggs_sweater",
    "briggs_fatigues",
  ],
  TwoWestCloset: ["your_slacks", "your_silk_shirt", "your_black_shoes"],
  FourEastCloset: ["kira_skirt", "kira_cat_sweatshirt"],
  FiveEastCloset: [
    "alice_gi_top",
    "alice_gi_pants",
    "black_belt",
    "alice_sneakers",
  ],
  UmboltzFootlocker: [
    "CameraGun",
    "GelRound1",
    "GelRound2",
    "GelRound3",
    "BottleOfScotch",
    "Bitterchew",
    "MensLockerKey4",
  ],
  FiveWestMedicineChest: ["hornychewToo", "hairychew"],
  EeglerMedicineChest: ["Brinychew"],
  SixWestCloset: ["ed_white_shirt", "ed_pressed_pants", "wool_vest"],
  AdminOfficeWastebin: ["AdminOfficeWastebinNote"],
};

export const INITIAL_SURFACE_CONTENTS: Record<string, string[]> = {};

export const INITIAL_UNDER_CONTENTS: Record<string, string[]> = {
  SixWestBedding: ["SixWestDiary"],
  OneEastAreaRug: ["ParkPass"],
};
