import { DNAResult } from "@game/rules/dnaReader";

export const DNA_DATABASE: Record<string, DNAResult> = {
  FallenCorpse: {
    id: "bottomStairwellBody",
    title: `Discovered at Bottom of Stairwell`,
    loggedAtTurn: 0,
    causeOfDeath: `Blunt force head trauma`,
    name: "Mox Eegler",
    gender: "Male",
    age: 42,
    occupation: "Scientist",
    info: "Mox Eegler is a high-value citizen, recently downgraded from exemplary, who is in excellent standing with an acceptable social score.\nEegler has worked as a top-tier scientist for over twenty rotations, and is responsible for many significant breakthroughs, receiving many public accolades. That being said, over the course of his most recent rotation he has repeatedly questioned the Mayor's authority to what might normally be considered a consequential degree, though his long history and efforts have, so far, kept him in good standing.\nMajor social infractions include: Suspected Printing of a Controlled Item\nMinor social infractions include: Triggering a Nuisance Chemical Reaction in a Public Space. Overclocking an AI to Consciousness Levels Exceeding .037 Percent. Public Nudity.",
  },
  StairSixBody: {
    id: "StairwellSixBody",
    title: `Discovered on level six stairwell landing`,
    loggedAtTurn: 0,
    causeOfDeath: `Severe liquefactive necrosis`,
    name: "Joelson Dend",
    gender: "Male",
    age: 27,
    occupation: "3D Printer Technician",
    info: "Joelson Dend is a reliable citizen, and is in good standing with a respectable social score.\nHe has worked at the 3D Printing Facility for over twenty rotations with no major incidents.\nMinor social infractions include: Public Intoxication. Unwanted Sexual Advances. Unwanted Sexual Retreats.\n",
  },
  HeadlessCorpse: {
    id: "headlessHydroponicsCorpse",
    title: `Discovered on level six near Hydroponics`,
    loggedAtTurn: 0,
    causeOfDeath: `Decapitation`,
    name: "Mox Eegler",
    gender: "Male",
    age: 42,
    occupation: "Scientist",
    info: "Mox Eegler is a high-value citizen, recently downgraded from exemplary, who is in excellent standing with an acceptable social score.\nEegler has worked as a top-tier scientist for over twenty rotations, and is responsible for many significant breakthroughs, receiving many public accolades. That being said, over the course of his most recent rotation he has repeatedly questioned the Mayor's authority to what might normally be considered a consequential degree, though his long history and efforts have, so far, kept him in good standing.\nMajor social infractions include: Suspected Printing of a Controlled Item\nMinor social infractions include: Attempting to Hypnotize in a Public Space. Spoofing a Security Camera with Pornographic Imagery. Public Nudity.",
  },
  OmarkBoutrosCorpse: {
    id: "omarkBoutrosCorpse",
    title: `Discovered on level three just inside Vivarium Park`,
    loggedAtTurn: 0,
    causeOfDeath: `Severe liquefactive necrosis`,
    name: "Omark Boutros",
    gender: "Male",
    age: 41,
    occupation: "Power Grid Supervisor",
    info: "Omark Boutros is a high-value citizen, and is in excellent standing with an excellent social score.\nHe has worked in Utilities and the Power Grid for over twenty rotations now, and has shown exemplary initiative there. He currently holds the position of Supervisor.\nMinor social infractions include: Fornicating in a careless manner. Public intoxication. Attempting to solicit an intelligent robot.",
  },
  HalvedCorpse: {
    id: "HalvedCorpse",
    title: `Discovered on level three in the residential corridor`,
    loggedAtTurn: 0,
    causeOfDeath: `Complete traumatic transection through the lumbopelvic junction`,
    name: "Lil-Lilly Tendwick",
    gender: "Female",
    age: 23,
    occupation: "Saltwater Aquarium Technician",
    info: "Lil-Lilly Tendwick is a somewhat reliable citizen, and is in decent standing with a questionable social score.\nShe has worked in the Zoology Sector, specifically maintaining Zoology's massive saltwater aquarium, for five rotations now with no major incidents, and in fact initiating several improvements.\nMajor social infractions include: Disrespecting Authority.\nMinor social infractions include: Public Intoxication. Public Nudity. Public Fornication. Attempting to Seduce a Security Officer while On Duty. Pressuring Security Personnel to Use Narcotics While On Duty. Provocation of a Fractionally Conscious Intelligence. Revealing a Magician's Trick During a Performance. Interruption of a School Assembly. Inciting Social Discord. Defiance of a Lawful Order.",
  },
  SpinStageCyclistCorpse: {
    id: "SpinStageCyclistCorpse",
    title: "Discovered on gymnasium spin class stage",
    loggedAtTurn: 0,
    causeOfDeath: "Electrocution",
    name: "Myndy",
    gender: "Female",
    age: 24,
    occupation: "Spin class instructor",
    info: "Myndy (birth name Gwan Feegle) is a good citizen, and is in good standing, with a good social score.\nShe has worked in Vivarium Park for over ten rotations now, with seven of those spent as a trainer at the park gymnasium. By all accounts she is excellent at her job, and well liked by her peers.\nMinor social infractions include: Attempting to feed preserve animals.",
  },
  GymWeightRoomCrushedBody: {
    id: "GymWeightRoomCrushedBody",
    title: "Discovered in gymnasium weight room",
    loggedAtTurn: 0,
    causeOfDeath: "Traumatic thoracic compression",
    name: "Henk Umboltz",
    gender: "Male",
    age: 37,
    occupation: "Head of Aeneas Security",
    info: "Henk Umboltz is a top-tier citizen who is in excellent standing and an exemplary social score, in spite of some minor incidents. He has worked in security for over twenty rotations, and sat as Head of Security for seven rotations, with only a few, inconsequential incidents.\nMinor social infractions include: Bludgeoning of a minor without cause. Extortion. Witness intimidation. Filing a false police report. Falsifying a filed police report. Destruction of evidence. Planting of evidence. Intoxication while on duty. Suspect intimidation. Civil rights violations. Defiance of a Lawful Order. Issuance of an Unlawful Order.",
  },
};
