import { DNAResult } from "@game/rules/dnaReader";

export const DNA_DATABASE: Record<string, DNAResult> = {
  FallenCorpse: {
    id: "bottomStairwellBody",
    title: `Discovered at Bottom of Stairwell`,
    loggedAtTurn: 0,
    causeOfDeath: `Blunt force head trauma`,
    name: "John Doe",
    gender: "Male",
    age: 34,
    occupation: "Scientist",
    info: "That boy ain't right.",
  },
  StairSixBody: {
    id: "StairwellSixBody",
    title: `Discovered on level six stairwell landing`,
    loggedAtTurn: 0,
    causeOfDeath: `Severe liquefactive necrosis`,
    name: "Joelson Dend",
    gender: "Male",
    age: 27,
    occupation: "3D Printer Technician",
    info: "Joelson Dend is a reliable citizen, and is in good standing with a respectable social score.\nHe has worked at the 3D Printing Facility for over twenty rotations with no major incidents.\nMinor social infractions include: Public Intoxication. Unwanted Sexual Advances. Unwanted Sexual Retreats.\n",
  },
  HeadlessCorpse: {
    id: "headlessHydroponicsCorpse",
    title: `Discovered on level six near Hydroponics`,
    loggedAtTurn: 0,
    causeOfDeath: `Decapitation`,
    name: "John Doe",
    gender: "Male",
    age: 34,
    occupation: "Scientist",
    info: "That boy ain't right.",
  },
  OmarkBoutrosCorpse: {
    id: "omarkBoutrosCorpse",
    title: `Discovered on level three just inside Vivarium Park`,
    loggedAtTurn: 0,
    causeOfDeath: `Severe liquefactive necrosis`,
    name: "Omark Boutros",
    gender: "Male",
    age: 41,
    occupation: "Power Grid Supervisor",
    info: "Omark Boutros is a high-value citizen, and is in excellent standing with an excellent social score.\nHe has worked in Utilities and the Power Grid for over twenty rotations now, and has shown exemplary initiative there. He currently holds the position of Supervisor.\nMinor social infractions include: Fornicating in a careless manner. Public intoxication. Attempting to solicit an intelligent robot.",
  },
};
