export const secretOrganismMessage = `ALIEN LIFEFORM DETECTED CONTACT INITIATED GENETIC HANDSHAKE INITIATED LIFEFORM GENETIC SEQUENCE DECODED GENETIC SEQUENCE MAPPED EXCHANGE INITIATED ANALYSIS FIRST EXCHANGE SEQUENCE BLOCK (800M BASE PAIRS) INITIATED EVALUATION INITATED PARSING PARSING PARSING FIRST EXCHANGE SEQUENCE BLOCK COMPLETE ASSESSING SECOND EXCHANGE SEQUENCE BLOCK (800M BASE PAIRS) INITIATED EVALUATION INITIATED PARSING PARSING FIRST SEQUENCE BLOCK ASSESSING RANKING SECOND EXHANGE SEQUENCE BLOCK COMPLETE ASSESSING THIRD EXCHANGE SEQUENCE BLOCK (800M BASE PAIRS) INITIATED EVALUTATION INITIATED PARSING PARSING PARSING SECOND SEQUENCE BLOCK ASSESSING RANKING THIRD EXHANGE SEQUENCE BLOCK COMPLETE ASSESSING FOURTH SEQUENCE BLOCK (800M BASE PAIRS) INITIATED EVALUATION INITIATED PARSING PARSING THIRD SEQUENCE BLOCK ASSESSING RANKING FOURTH EXCHANGE SEQUENCE BLOCK COMPLETE ASSESSING EVALUATION COMPLETE ALIEN LIFEFORM SEQUENCING FIRST BLOCK 94 PERCENT DEPRECIATED SECOND BLOCK 47 PERCENT DEPRECIATED THIRD BLOCK 19 PERCENT DEPRECIATED FOURTH BLOCK 82 PERCENT DEPRECIATED ANALYSIS UPGRADE DEPRECIATED SEQUENCES INCORPORATE MARKED NOVEL SEQUENCE PAYLOAD 6 PERCENT UPGRADE DEPRECIATED SEQUENCES ALIEN LIFEFORM UPGRADE SUCCESSFUL ALIEN LIFEFORM UPGRADE COMPLETE`;

export const cipheredSecretOrganismMessage = `FFVGG TWSMSUWG QGMMQGMQ ITHGCVB WAQGOFNRF ZMBRBVI MUAFLPOXM VTNNVCMMR YQSKKIEO ZMBRBVI XYDWXVQR LRITXRF ZMBRBVI XYDWXVQR UNVUYQ GQKVNVTK NHVVBIHRL NTFFLUBA TVZFZ JRPJTVUR ARWZYAEX JZBKX (800S GUFG IIWEA) VTNNVCMMR RDNRZUGKHV WAQGGYYQ RTZGVVT VFLFKGO DNZFOSA SKKAH RFPNFHTG LMEHMAIJ VYQVS QBUCRJNR CLASFAVTL MREHVR RFPNFHTG LMEHMAIJ VYQVS (800A OIFK UUVTL) QBVBVGYYQ GOIZHIGOTH VPBBWNBRJ UUEUBVU CIEYNHT HBZGG ARWZYAEX JZBKX GXMRULQBT ZNTPCAI LMQBVQ KCBNPZM GRYHKSWR DEWQX KBSUFRVX IGFMFYNHT VAQFQ MKIMUAIX ASDCRTHY ONHKY (800Z JNYJ JNKKA) WAQGOFNRF XDOYCGGYCBP BVWGQNZJX CCKAWAO CGWMVPZ XOEAVTL MREHVR FMDAJHPG UTCPS NYXYFUBVU EIAQNHT VAQFQ MKNFHTG LMEHMAIJ VYQVS QBUCRJNR CLASFAVTL ZBWKBV FMDAJHPG UTCPS (800Z HFMR RTQFF) QAOYCNVXL SIIYAFNVQG QBVBVGYYQ RTZGVVT VFLFKGO HUQEJ XYDWXVQR JYUHE NULMGFQAM WUAMBVU SWHXYB RZVPOAOR YJKHGGKS OTBIP WBOITSGM NYXYFUBVU RDNRZUGKHV QBUCRJNR CEQSA TVLJZBTF ASDCRTHCAI YQFFB ORTWX 94 RXZQRVG JJJEGVQOGMQ YJWBPW JZBKX 47 VJLPGGB RRXEKHCNVXL HUQEJ GFBED 19 XSEKRTY XRRKMQVIGKI ZBWKBV OTBIP 82 JRTVMBG LRVWYPKTBSQ IAGQSFKL CDTZNJJ XRRKMQVIGKI MRSNMBPMF OSWBTIWFNBR SFLXGW VCIMY YJKHGGKS CILRTUQ 6 RXZQRVG AUAECWM RRXEKHCNVXL GRYHKSWRU TTWRV YOKYSQKU ICOEGIY FWVKSFASAQ UYKXV ZVNRLTLZ WIOFNLR ITGCNXBS`;

export const SYNDROME_X_SIGNAL_LOG_SOURCE = "syndrome x signal";
export const SYNDROME_X_SIGNAL_TRANSCRIPT_NOTE =
  "...you're not sure what that was, but you make a note of it in case it's important.";

export const SYNDROME_X_SIGNAL_FRAGMENT_COUNT = 13;
const SYNDROME_X_SIGNAL_FRAGMENT_BASE_WEIGHT = 6;

export function getSyndromeXSignalFragment(index: number): string | null {
  if (index < 0 || index >= SYNDROME_X_SIGNAL_FRAGMENT_COUNT) return null;

  const words = cipheredSecretOrganismMessage.split(/\s+/);
  const totalWeight =
    (SYNDROME_X_SIGNAL_FRAGMENT_COUNT *
      (2 * SYNDROME_X_SIGNAL_FRAGMENT_BASE_WEIGHT +
        SYNDROME_X_SIGNAL_FRAGMENT_COUNT -
        1)) /
    2;
  const weightBefore =
    (index *
      (2 * SYNDROME_X_SIGNAL_FRAGMENT_BASE_WEIGHT + index - 1)) /
    2;
  const weightThrough =
    ((index + 1) *
      (2 * SYNDROME_X_SIGNAL_FRAGMENT_BASE_WEIGHT + index)) /
    2;

  const start = Math.floor((words.length * weightBefore) / totalWeight);
  const end = Math.floor((words.length * weightThrough) / totalWeight);

  return words.slice(start, Math.max(end, start + 1)).join(" ");
}
