import { Item } from "@game/types/itemTypes";
import { Room } from "@game/types/roomTypes";

export const threeEastRooms: Room[] = [
  // LIVING QUARTERS THREE EAST
  {
    id: "LivingQuartersThreeEast",
    name: "Eegler Residence: Living Area",
    description: `You're standing in the entryway of a large living space which has been divided into two distinct sections; the first is a TV area where [[SCENERY]]`,
    exits: [
      { direction: "west", doorId: "DOOR3CE" },
      { direction: "south", doorId: "ThreeEastBDoor" },
      { direction: "east", toRoomId: "ThreeEastBed" },
    ],
  },
  {
    id: "ThreeEastBath",
    name: "Eegler Residence: Bathroom",
    description: `The bathroom is dominated by [[SCENERY]]`,
    exits: [{ direction: "north", doorId: "ThreeEastBDoor" }],
  },
  {
    id: "ThreeEastBed",
    name: "Eegler Residence: Bedroom",
    description: `The bedroom feels familiar to you somehow, with [[SCENERY]]`,
    exits: [
      { direction: "west", toRoomId: "LivingQuartersThreeEast" },
      { direction: "down", toRoomId: "SecretLab" },
    ],
  },
  {
    id: "SecretLab",
    name: "Eegler Residence: Secret Lab",
    description: `This is a somewhat small space that borders somewhere between cozy and cluttered, with [[SCENERY]]`,
    exits: [{ direction: "up", toRoomId: "ThreeEastBed" }],
  },
];

export const threeEastItems: Item[] = [
  // Secret Lab
  {
    id: "SecretLabWorkspace",
    name: "workspace",
    description: "You know this setup, you've worked here before.",
    sceneryDescription:
      "a workspace covered in electronics taking up a lot of the room. ",
    location: "SecretLab",
    vocab: ["workspace"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 1,
    },
  },
  {
    id: "SecretLabLaptops",
    name: "laptops",
    description:
      "They're top of the line, and they all seem very familiar somehow.",
    sceneryDescription: "There's a total of three laptops ",
    location: "SecretLab",
    vocab: ["laptops", "laptop", "computers", "computer"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 2,
    },
  },
  {
    id: "SecretLabMonitors",
    name: "monitors",
    description: "They're all large, with plenty of real estate.",
    sceneryDescription: "and six flatscreen monitors in and among ",
    location: "SecretLab",
    vocab: ["monitor", "monitors", "screen", "screens"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 3,
    },
  },
  {
    id: "SecretLabEquipment",
    name: "electronic equipment",
    description: "Somebody's been as busy as a bee down here.",
    sceneryDescription:
      "other electronic devices, some stacked on top of one another, that seem to be various scanners, analyzers, and other assorted testing equipment.",
    location: "SecretLab",
    vocab: [
      "electronics",
      "devices",
      "electronic",
      "device",
      "testing",
      "scanner",
      "scanners",
      "analyzer",
      "analyzers",
    ],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 4,
    },
  },
  {
    id: "SecretLabPrinter",
    name: "3d printer",
    description:
      "It's some kind of hand built 3D printer which, while not sophisticated, looks capable of printing small, even complex objects and tools, if it were getting any power. If the unit was unauthorized, it might have been used to create something in secret.",
    sceneryDescription:
      "[[newline]]In one corner, tucked under the workspace, you can see a heavy looking metal barrel or tank fitted to various electronics, including a small display screen.",
    location: "SecretLab",
    vocab: ["barrel", "cylinder", "printer", "3d"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 5,
    },
    overrides: {
      use: `It's not getting any power and anyway, it looks like it's empty to boot.`,
    },
  },
  {
    id: "SecretLabPhoto",
    name: "photograph",
    description:
      "The man in the photo sits behind a desk and is wearing a tailored suit, but he's heavyset, with a heavy brow and thick fingers like he'd be more at home twisting people into pretzels. His nametag reads 'Umboltz' but this guy isn't the head of security. Something about him makes you bristle. You don't like this guy.",
    sceneryDescription:
      "[[newline]]On the wall over the work area is taped a photo of a heavyset man with thick fingers and a prominent nose, wearing a nametag that reads 'Umboltz'.",
    location: "SecretLab",
    vocab: ["picture", "photo", "photograph"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 6,
    },
  },
  {
    id: "Dart",
    name: "dart",
    description:
      "It's a little metallic red dart, like something pulled from a pub's dartboard.",
    initialDescription:
      "There is a red metallic dart stuck through the photo and into the wall behind it, piercing the man's grinning face.",
    location: "SecretLab",
    vocab: ["dart", "red", "metallic"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 20,
    itemSize: 4,
  },
  {
    id: "MindGun",
    name: "electronic scanner",
    vocab: [
      "mind",
      "memory",
      "extractor",
      "cylinder",
      "antenna",
      "sensor",
      "reader",
      "scanner",
      "electronic",
    ],
    description:
      "It's not immediately clear what the device does. It has a grip at one end, and at the other end is a cylinder wrapped in a fine wire mesh that seems like it's meant to be pointed at things, so perhaps a scanner of some sort. Whatever it is, it doesn't look like it came off of an assembly line or printer and has a lot of exposed wires and circuitry.",
    initialDescription:
      "Sitting on the workstation desk is some kind of hand-held scanning device with visible electronics and wires clustered near the base where the grip to hold it is.",
    location: "SecretLab",
    meta: {
      onLoad: "It doesn't seem to take any ammo, nor does it have a barrel.",
      onLink:
        "The strangest feeling washes over you and you feel a wave of intense dizziness which passes almost instantly. In your head, a soft voice which is not your own says 'Link established...', and before you can even wonder what that means you suddenly sense a flood of thoughts pouring into your mind...thoughts which are not yours...",
      onShootNoCap:
        "As you pull the trigger the gun lets out a extremely low hum that sets your teeth on edge, but nothing else seems to happen.",
      onShootWithCap:
        "As you pull the trigger the gun lets out a extremely low hum that sets your teeth on edge, and you feel your scalp tingle underneath the electronic cap.",
    },
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 2,
    itemSize: 2,
    isShootable: true,
  },
  {
    id: "MindCap",
    name: "wired cap",
    vocab: ["cap", "headdress", "squid"],
    description:
      "The cap consists of a series of silvery components meshed together in a web with some kind of metallic filaments all run through a stretchy fabric which can be fitted over the head.",
    initialDescription:
      "Draped over one of the laptop screens is some sort of fabric cap that can be worn on the head.",
    location: "SecretLab",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: true,
    clothingSlot: "head",
  },
  {
    id: "DNAReader",
    name: "slim electronic wand",
    description:
      "A slim electronic wand about a foot long, ending in a small porous bulb for collecting and analyzing trace samples.",
    initialDescription:
      "On one corner of the desk sits a handheld wand of some kind, with a grip at one end and a foam bulb at the other.",
    location: "SecretLab",
    vocab: ["dna", "sampler", "analyzer", "reader", "wand"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
  },
  {
    id: "SecretInstructions",
    name: "Device Instructions",
    description: "It seems to be some kind of handwritten instructions.",
    initialDescription:
      "On the workstation desk is a paper note, packed with dense lines of text.",
    location: "SecretLab",
    vocab: ["paper", "note", "instructions"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 20,
    itemSize: 4,
    isReadable: true,
    isLoggable: true,
    readableText: `Mind Gun / Mind Extractor\n\nI'm still working on a name, but the device now functions exactly as designed. It works in tandem with the electrode cap, so you need both for it to work. Once the cap is on your head, all you need to do is point at the head of the target, and shoot. The device has two modes but it auto-detects so you don't have to change the setting:\n\nOn Living Targets: When used on a living target the Extractor scans the target's active brainwaves, compiles them, then pipes the output to the wielder, who is able to effectively 'read' the target's thoughts, to a degree.\n\nOn Deceased Targets: When the Extractor is used on a non-living target that still has intact brain tissue, it scans topography and extracts a sample using my patented technique. If viable, it reconstructs the randomly selected memory and replays it for the wielder, who experiences the memory first hand, at least in a fashion.\n\nThere's still testing to do; if it ever does the sample extraction on a living target I'm not sure exactly what will happen but it wouldn't be good. They want it smaller, too, but functionally, it works.\n\nThe DNA sampler wand is ready, too, wasn't too complicated but should be pretty useful.`,
  },
  // Bedroom
  {
    id: "EeglerBed",
    name: "double bed",
    description: "It looks comfortable, and familiar to you.",
    sceneryDescription: "a double bed situated in one corner, ",
    location: "ThreeEastBed",
    vocab: ["double", "bed"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 1,
    },
  },
  {
    id: "EeglerDresser",
    name: "wooden dresser",
    description: "It's made from wood and has several drawers.",
    sceneryDescription: "and a wooden dresser across from that. ",
    location: "ThreeEastBed",
    vocab: ["wooden", "dresser"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isContainer: true,
    isOpenable: true,
    meta: {
      sceneryDescriptionOrder: 2,
    },
  },
  {
    id: "EeglerLavaLamp",
    name: "lava lamp",
    description: "The wax moves around lazily inside the liquid.",
    sceneryDescription:
      "Sitting on top of the dresser is a lava lamp with orange liquid, yellow wax, and a black base casting the room in an orange glow, ",
    location: "ThreeEastBed",
    vocab: ["lava", "lamp", "lavalamp"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 3,
    },
    overrides: {
      switch: `You don't see any obvious switch.`,
    },
  },
  {
    id: "EeglerFrame",
    name: "picture frame",
    description:
      "In the photo, a man with receding blond hair stands smiling next to a woman with long brown hair, who is also smiling. They have their arms around each other in a casual way.",
    sceneryDescription:
      "and next to that is a small framed picture of a man and a woman standing next to each other and smiling.",
    location: "ThreeEastBed",
    vocab: ["picture", "photo", "frame"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 4,
    },
  },
  {
    id: "EeglerPhone",
    name: "phone",
    description: `It's a phone with an integrated message system.`,
    sceneryDescription: `[[newline]]Between the lamp and the picture frame sits a phone messaging system dressed in a sleek black plastic shell.`,
    location: "ThreeEastBed",
    vocab: ["message", "system", "message system", "machine", "messages"],
    itemClass: "solid",
    itemCategory: "scenery",
    isUseable: true,
    meta: {
      sceneryDescriptionOrder: 5,
      kind: "phone",
      messages: [
        {
          id: "3EM1",
          title: "CALLER ID: FICK, YOLONOPE",
          transcript: `Hi, it's me, I just wanted to call and thank you again for coming by the classroom the other day and doing all of those demonstrations for my students, they absolutely loved it. See, you didn't need to worry, you did great, I'm telling you you're still the talk of the town around here, in fact you might have generated real interest in a couple of the little buggers. I love that you did that, and I love you.`,
        },
        {
          id: "3EM2",
          title: "CALLER ID: FICK, YOLONOPE",
          transcript: `Mox, I've discovered something very alarming and we need to talk about it right away, as soon as you can. First off, I know how you feel about privacy but that little wall lamp wasn't exactly fooling anybody was it? And how long was I supposed to pretend I didn't know something was down there? I knew it was something, but that? If they ever found out that you printed that thing, you'd be in serious trouble. I took it, I left the rest of it but I took it and I put it in my safe, and you should be glad I did. Please, I know how hard this is, believe me, it's hard for me, too, it feels impossible sometimes that we won't see each other again, and I will never forget how far you were, and are, willing to go to keep us together but I won't let you throw your life away, I'm sorry. I know you think you're irreplaceable, and maybe you are, but nobody is so crucial they can just cross any line and not pay a price. You need to come talk to me, as soon as you can. Please.`,
        },
        {
          id: "3EM7",
          title: "CALLER ID: AENEAS POPULATION AND LOGISTICS ADMINISTRATION",
          transcript: `Mister Eegler, I feel like I've made this call before in the past, many times, and while I know things turned a bit heated as of late, I wanted to assure you that I honestly, seriously, take no pleasure in delivering these rejections, in fact it's the opposite. I know you loathe the ground I stand on but whether you believe it or not, I truly do admire the work and detail you've put into your case, you really do have a strong case, and I truly do admire your passion. I am not a heartless man, and it pains me to deliver this news again and again, but the Mayor has held firm, and as you well know, the Mayor gets the final say. These audiences are difficult to arrange and to justify. The Mayor understands things on a level that we can't, so stop second guessing!`,
        },
      ],
      unreadCount: 0,
      redFlashCount: 0,
    },
    itemWeight: 0,
    itemSize: 0,
  },
  {
    id: "EeglerWallFixture",
    name: "wall fixture",
    description:
      "The light fixture is somewhat conspicuous. It sprouts from the wall then does a ninety degree turn toward the ceiling, and on closer inspection it looks like the whole unit can be rotated.",
    sceneryDescription:
      "[[newline]]The other side of the room has a large open space cleared on the floor, and on the wall above the spot is a mounted light fixture with a wire-ribbed shade.",
    location: "ThreeEastBed",
    vocab: [
      "wall",
      "light",
      "fixture",
      "light fixture",
      "wall fixture",
      "wall light fixture",
    ],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 6,
    },
    isTurnable: true,
  },
  // Bathroom
  {
    id: "EeglerTub",
    name: "soaking tub",
    description:
      "It's nice and deep with places to comfortably sit. It could fit two, or even four.",
    sceneryDescription:
      "a large, square soaking tub that sits in the southwest corner of the room, at the moment completely dry. ",
    location: "ThreeEastBath",
    vocab: ["tub", "soaking"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 1,
    },
  },
  {
    id: "ThreeEastBathroomSink",
    name: "sink",
    description:
      "A stained bathroom sink with a squat faucet and a slow, reliable trickle of water.",
    sceneryDescription:
      "Next to that is a porcelain sink with faucet handles for both hot and cold, ",
    location: "ThreeEastBath",
    vocab: ["sink", "faucet", "tap", "water"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    meta: {
      sceneryDescriptionOrder: 2,
      watersource: {
        onTake: "You run the tap and collect some water",
      },
    },
    overrides: {
      turn: `You turn the faucet and a slow trickle of water runs into the basin.`,
    },
    isTurnable: true,
  },
  {
    id: "EeglerMedicineChest",
    name: "medicine chest",
    description: "It's utilitarian and clean.",
    sceneryDescription: "a medicine chest mounted on the wall above it whose ",
    location: "ThreeEastBath",
    vocab: [
      "medicine",
      "cabinet",
      "medicine cabinet",
      "chest",
      "medicine chest",
    ],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isContainer: true,
    isOpenable: true,
    meta: {
      sceneryDescriptionOrder: 3,
    },
  },
  {
    id: "EeglerMedicineChestMirror",
    name: "mirror",
    description: "The glass is spotless.",
    sceneryDescription: "mirrored door reflects your face back at you. ",
    location: "ThreeEastBath",
    vocab: ["mirror"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isReflective: true,
    meta: {
      sceneryDescriptionOrder: 4,
    },
  },
  {
    id: "EeglerToilet",
    name: "porcelain toilet",
    description: `It's clean, and devoid of water.`,
    sceneryDescription: `In the corner opposite the tub sits a pristine white toilet.`,
    location: "ThreeEastBath",
    vocab: ["toilet", "bowl", "toilet bowl"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 2,
    itemSize: 3,
    meta: {
      sceneryDescriptionOrder: 5,
    },
  },
  {
    id: "Brinychew",
    name: "briny chewable",
    description: `It's a small, brick-shaped chewable inside a thin papery wrapper. The light blue wrapper displays a high-tech logo for something called 'CorteXtra' which promises it contains DNA from real ancient jellyfish that will boost your intelligence. It also promises, in tiny print, that the wrapper is also edible.`,
    initialDescription: `an individually wrapped chewable sits on one shelf of the medicine chest.`,
    location: "seeded",
    vocab: ["chewable", "gummy", "briny", "cortextra"],
    itemClass: "solid",
    itemCategory: "collectable",
    meta: {
      consumable: {
        kind: "food",
        perDose: [
          { type: "status", id: "smarter", intensity: 100, duration: 10000 },
          {
            type: "message",
            text: `You pop the chewable in your mouth and squish it between your back teeth. It yields like gum for a moment, then dissolves all at once into a briny syrup. You can really taste the jellyfish!`,
          },
        ],
        onEmpty: [{ type: "message", text: "It's empty." }],
      },
    },
    itemWeight: 2,
    itemSize: 3,
    isConsumable: true,
    doses: 1,
  },
  // Living Area
  {
    id: "EeglerSofa",
    name: "brown sofa",
    description:
      "The sofa looks quite comfortable, with soft brown upholstery and cushions, and could seat two comfortably.",
    sceneryDescription:
      "a light brown sofa with carved wooden legs is positioned in front of ",
    location: "LivingQuartersThreeEast",
    vocab: ["sofa", "couch", "brown"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isSurface: true,
    meta: {
      sceneryDescriptionOrder: 1,
    },
  },
  {
    id: "EeglerCoffeeTable",
    name: "coffee table",
    description:
      "It's a low wooden coffee table with a surface marred by a few water rings.",
    sceneryDescription: "a coffee table, facing toward ",
    location: "LivingQuartersThreeEast",
    vocab: ["coffee", "table", "wooden"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isSurface: true,
    meta: {
      sceneryDescriptionOrder: 2,
    },
  },
  {
    id: "EeglerTV",
    name: "flatscreen tv",
    description: `It doesn't seem to be getting any signal at the moment.`,
    sceneryDescription: `a large flatscreen whose screen is dark. `,
    location: "LivingQuartersThreeEast",
    vocab: ["flatscreen", "tv", "television"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 3,
      onSwitch: `You turn it on and off, but nothing happens.`,
    },
    itemWeight: 2,
    itemSize: 3,
    isSwitchable: true,
  },
  {
    id: "EeglerWatercolor",
    name: "watercolor painting",
    description: `It's a beautiful painting, with all the details of the countryside painted only in the barest moonlight. The cottage looks like warm point of light in a vast ocean underneath a starry sky.`,
    sceneryDescription: `On the wall next to the TV hangs a large watercolor painting of a country landscape at night, barely lit by moonlight, with a small, lit cottage in the distance. `,
    location: "LivingQuartersThreeEast",
    vocab: ["painting", "watercolor", "countryside", "cottage"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 4,
    },
    itemWeight: 2,
    itemSize: 3,
  },
  {
    id: "EeglerCarpet",
    name: "shag carpet",
    description: `The carpet has seen a lot of wear, footprints overlapping footprints.`,
    sceneryDescription: `The other half of the room is devoted to some a small music studio, boundaries marked by a section of plush, russet-colored shag carpet. `,
    location: "LivingQuartersThreeEast",
    vocab: ["carpet", "shag"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 5,
    },
    itemWeight: 2,
    itemSize: 3,
  },
  {
    id: "EeglerAmps",
    name: "amplifiers",
    description: `They're boxy, built to last, and look like they're capable of generating some real noise, though they're without power at the minute.`,
    sceneryDescription: `Stacked along the wall are a series of amplifiers, `,
    location: "LivingQuartersThreeEast",
    vocab: ["amps", "amplifiers"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 6,
    },
    itemWeight: 2,
    itemSize: 3,
  },
  {
    id: "EeglerPedals",
    name: "pedals",
    description: `They're wired between the guitar and the amps. You're not sure what they do but one has a label that says 'Wah' one says 'Phase' and the last one says 'Dist'.`,
    sceneryDescription: `and you also see a pair of foot pedals in and among trailing music cables. `,
    location: "LivingQuartersThreeEast",
    vocab: ["pedal", "pedals"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 6,
    },
    itemWeight: 2,
    itemSize: 3,
  },
  {
    id: "EeglerSheetMusic",
    name: "sheet music",
    description: `It's all handwritten and scribbled, pieces of different working projects.`,
    sceneryDescription: `Here and there on the floor are stray pages of sheet music, written in a precise hand.`,
    location: "LivingQuartersThreeEast",
    vocab: ["sheet", "music"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 7,
    },
    itemWeight: 2,
    itemSize: 3,
  },
  {
    id: "EeglerGuitar",
    name: "electric guitar",
    description: `A '57 Higgenbottom Quantumcaster with Wakashi pickups and a whammy bar. You’re not entirely sure what any of that entails, but it screams top of the line. The body has a sleek black finish, offset by chrome machine heads and a bridge polished to a mirror shine.`,
    initialDescription: `Leaning against one of the amplifiers is a slick-looking electric guitar, black and polished to a shine.`,
    location: "LivingQuartersThreeEast",
    vocab: ["electric", "guitar", "axe"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 2,
    itemSize: 3,
  },
];
