import type { Item } from "../types";

export const drugItems: Item[] = [
  {
    id: "Syringe",
    name: "syringe",
    description:
      "A heavy hypodermic syringe with a clamp for holding drug cartridges.",
    initialDescription: "Lying amongst the mess is a large syringe.",
    location: "MedicalStorage",
    vocab: ["syringe", "hypodermic", "needle"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: true,
  },
  {
    id: "GroovyCart",
    name: "green serum cartridge",
    description:
      "A translucent cartridge filled with green serum, labeled ‘TRIXOPHINE’.",
    location: "DRUGTIN",
    vocab: ["green", "serum", "cartridge", "trixophine"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
  },
  {
    id: "RadBGoneCart",
    name: "red serum cartridge",
    description:
      "A translucent cartridge filled with red serum, labeled ‘SERITROXIN’.",
    location: "LevelThreeSecretRoom",
    vocab: ["red", "serum", "cartridge", "seritroxin"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
  },
  {
    id: "DeathCart",
    name: "white serum cartridge",
    description:
      "A translucent cartridge filled with white serum, labeled ‘PENTATROSIN’.",
    initialDescription:
      "A cylindrical cartridge filled with white serum sits on one of the beds.",
    location: "UNKNOWN", // TODO: set correct room id
    vocab: ["white", "serum", "cartridge", "pentatrosin"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
    // TODO: handle syringe-related logic later
  },
  {
    id: "NANOCart",
    name: "silver serum cartridge",
    description: "A translucent cartridge filled with silver serum, unlabeled.",
    initialDescription: "A cylindrical cartridge lies on one of the tables.",
    location: "RemoteMedicalTwo",
    vocab: ["silver", "serum", "cartridge"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
  },
  {
    id: "InocCart",
    name: "clear serum cartridge",
    description:
      "A translucent cartridge filled with clear serum, labeled ‘EXPERIMENTAL’.",
    initialDescription: "A cylindrical cartridge sits on one of the tables.",
    location: "UNKNOWN", // TODO
    vocab: ["clear", "serum", "cartridge", "experimental"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
  },
  {
    id: "SleepyCart",
    name: "yellow serum cartridge",
    description:
      "A translucent cartridge filled with yellow serum, labeled ‘XANTOPHOL’.",
    initialDescription: "A small yellow-serum cartridge rests on a shelf.",
    location: "Lab",
    vocab: ["yellow", "serum", "cartridge", "xantophol"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
  },
  {
    id: "PainKillerCart",
    name: "amber serum cartridge",
    description:
      "A translucent cartridge filled with amber serum, labeled ‘VANITRAX’.",
    initialDescription: "A small amber-serum cartridge rests on a shelf.",
    location: "PatientCareTwo",
    vocab: ["amber", "serum", "cartridge", "vanitrax"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    hasDose: true,
  },
];
