import type { Item } from "../types";

export const drugItems: Item[] = [
  {
    id: "Syringe",
    name: "a medical syringe",
    description:
      "A heavy hypodermic syringe with a spring-clamp assembly for holding drug cartridges.",
    initialDescription:
      "Lying amidst the clutter is a large hypodermic syringe.",
    location: "Dresser", // inside the dresser to start
    vocab: ["syringe", "hypodermic", "needle"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 1,
    contains: [],
    allowedContentsIds: [
      "GroovyCart",
      "RadBGoneCart",
      "DeathCart",
      "NANOCart",
      "InocCart",
      "SleepyCart",
      "PainKillerCart",
    ],
  },
  {
    id: "Dresser",
    name: "dresser",
    description:
      "A scarred wooden dresser with several misaligned drawers and a faint chemical smell.",
    sceneryDescription:
      "Against the wall sits a battered wooden dresser, its drawers slightly ajar as if searched in a hurry.",
    location: "LivingQuartersFiveEast",
    vocab: ["dresser", "drawers", "bureau"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 100,
    itemSize: 20,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: true,
    capacity: 8,
    contains: ["Syringe"],
  },

  {
    id: "GroovyCart",
    name: "green serum cartridge",
    description:
      "A translucent cartridge filled with green serum, labeled ‘TRIXOPHINE’.",
    location: "INVENTORY", //"DRUGTIN",
    vocab: ["green", "serum", "cartridge", "trixophine"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    injectionEffectId: "trixophine",
    doses: 3,
  },
  {
    id: "RadBGoneCart",
    name: "red serum cartridge",
    description:
      "A translucent cartridge filled with red serum, labeled ‘SERITROXIN’.",
    location: "LevelThreeSecretRoom",
    vocab: ["red", "serum", "cartridge", "seritroxin"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    doses: 1,
  },
  {
    id: "DeathCart",
    name: "white serum cartridge",
    description:
      "A translucent cartridge filled with white serum, labeled ‘PENTATROSIN’.",
    initialDescription:
      "A cylindrical cartridge filled with white serum sits on one of the beds.",
    location: "UNKNOWN", // TODO: set correct room id
    vocab: ["white", "serum", "cartridge", "pentatrosin"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    doses: 5,
    // TODO: handle syringe-related logic later
  },
  {
    id: "NANOCart",
    name: "silver serum cartridge",
    description: "A translucent cartridge filled with silver serum, unlabeled.",
    initialDescription: "A cylindrical cartridge lies on one of the tables.",
    location: "RemoteMedicalTwo",
    vocab: ["silver", "serum", "cartridge"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    doses: 1,
  },
  {
    id: "InocCart",
    name: "clear serum cartridge",
    description:
      "A translucent cartridge filled with clear serum, labeled ‘EXPERIMENTAL’.",
    initialDescription: "A cylindrical cartridge sits on one of the tables.",
    location: "UNKNOWN", // TODO
    vocab: ["clear", "serum", "cartridge", "experimental"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    doses: 1,
  },
  {
    id: "SleepyCart",
    name: "yellow serum cartridge",
    description:
      "A translucent cartridge filled with yellow serum, labeled ‘XANTOPHOL’.",
    initialDescription: "A small yellow-serum cartridge rests on a shelf.",
    location: "Lab",
    vocab: ["yellow", "serum", "cartridge", "xantophol"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    doses: 3,
  },
  {
    id: "PainKillerCart",
    name: "amber serum cartridge",
    description:
      "A translucent cartridge filled with amber serum, labeled ‘VANITRAX’.",
    initialDescription: "A small amber-serum cartridge rests on a shelf.",
    location: "PatientCareTwo",
    vocab: ["amber", "serum", "cartridge", "vanitrax"],
    itemClass: "liquid",
    itemCategory: "fluid",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    isSyringeCartridge: true,
    doses: 5,
  },
];
