import type { Item } from "../types";

export const levelOneItems: Item[] = [
  {
    id: "BridgeGreyIND",
    name: "indicator light",
    description:
      "A circular indicator disk is set flush into the bulkhead, glowing with an unnervingly calm grey light.",
    initialDescription: "The disk is glowing with a cold, grey light.",
    sceneryDescription:
      "The small disk emits a steady, washed-out grey glow that doesn’t flicker or pulse. It throws a thin halo across the metal wall, bleaching nearby controls of color and warmth.",
    location: "Bridge",
    vocab: ["indicator", "light", "glow", "disk", "grey"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "BridgeFigures",
    name: "human figures",
    description:
      "Silhouetted against the dead glow of the consoles, the human figures remain slumped at their stations, frozen in place.",
    sceneryDescription:
      "The crew shapes are little more than dark outlines now—heads bowed, shoulders sagging, limbs splayed in the way of people who never expected not to get back up. Harnesses still cut across their chests like seatbelts on crash test dummies.",
    location: "Bridge",
    vocab: ["human", "figures", "silhouettes", "crew", "bodies"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "CaptainHead",
    name: "head",
    description:
      "The Captain’s head is tilted slightly to one side. It’s not moving.",
    sceneryDescription:
      "The skin has gone slack and pale, eyes half-lidded and unfocused. Whatever expression was there when he died has long since drained away, leaving a bland, unsettling calm.",
    location: "Bridge",
    vocab: ["head", "captain", "captain's head"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 5,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "RedFlashingLightBridge",
    name: "flashing red light",
    description:
      "A red indicator light flashes rhythmically; on for two seconds, then off for three, over and over again.",
    sceneryDescription:
      "The light pulses like a mechanical heartbeat stitched into the bridge, bathing nearby panels in intermittent crimson. In the gaps between flashes, the silence feels a shade heavier.",
    location: "Bridge",
    vocab: ["flashing", "red", "light", "lights", "indicator"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "RedFlashingLightBridgeCaptain",
    name: "flashing red light",
    description:
      "Above the Captain’s station, a red light flashes with relentless precision—two seconds on, three seconds off.",
    sceneryDescription:
      "Each flash paints the Captain’s chair and console in blood-red for a moment, then snatches the color away again, as if reconsidering.",
    location: "BridgeCaptain",
    vocab: ["flashing", "red", "light", "alert"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "RedFlashingLightBridgeHelm",
    name: "flashing red light",
    description:
      "A red warning light stutters its steady pattern over the helm console, indifferent to the dead man slumped beside it.",
    sceneryDescription:
      "The pulse reflects off the console’s polished surfaces, turning frozen trajectory lines and dead readouts into brief splashes of red panic.",
    location: "BridgeHelm",
    vocab: ["flashing", "red", "light", "warning"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "RedFlashingLightBridgeTact",
    name: "flashing red light",
    description:
      "A red light over the tactical station continues its patient cycle; on for two seconds, off for three.",
    sceneryDescription:
      "The tactical console blinks in and out of harsh crimson relief, as if the ship is still trying to shout that something is very wrong, long after anyone was listening.",
    location: "BridgeTact",
    vocab: ["flashing", "red", "light"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "RedFlashingLightBridgeComm",
    name: "flashing red light",
    description:
      "A red indicator over the communications console blinks insistently, waiting for someone who isn’t coming back.",
    sceneryDescription:
      "Its cycle of light and dark sweeps across the comms panel, briefly catching empty chairs and dead screens in a bloody wash.",
    location: "BridgeComm",
    vocab: ["flashing", "red", "light"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "RedFlashingLightBridgeScience",
    name: "flashing red light",
    description:
      "Over the science station, a red light marks out five-second slices of a dead ship’s time.",
    sceneryDescription:
      "The science readouts and lab displays blink into existence and back into darkness in a regular, almost soothing pattern. Almost.",
    location: "BridgeScience",
    vocab: ["flashing", "red", "light"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "CommandChairDistant",
    name: "command chair",
    description:
      "From here, the central command chair looks imposing, elevated just enough to oversee every station on the bridge.",
    sceneryDescription:
      "The chair sits on a low dais, armrests studded with darkened controls. Even empty, it radiates the quiet authority of someone used to making decisions that kill people they’ll never meet.",
    location: "Bridge",
    vocab: ["command", "chair", "captain", "captain's", "seat"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "CaptainChair",
    name: "captain's chair",
    description:
      "Up close, the Captain’s chair looks like the perfect blend of functionality, stateliness, and comfort—designed for someone who has to look in control even while the universe is on fire.",
    sceneryDescription:
      "High-grade synth-leather upholstery has been worn smooth where elbows, shoulders, and bad decisions rested for years. Subtle controls are embedded along the armrests, now dark and unresponsive.",
    location: "BridgeCaptain",
    vocab: ["captain", "captain's", "chair", "seat"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MainViewerBridge",
    name: "main viewer",
    description:
      "The main viewer dominates the front of the bridge, currently showing only darkness and the faint suggestion of distant stars. Whatever was out there before is gone now.",
    sceneryDescription:
      "The surface is vast and slightly curved, a black mirror hanging over the ship’s collective anxiety. Reflected ghost-images of the bridge drift across the glass whenever the warning lights pulse.",
    location: "Bridge",
    vocab: ["main", "viewer", "viewscreen", "screen", "display"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MainViewerBridgeCaptain",
    name: "main viewer",
    description:
      "From the Captain’s station, the main viewer looms like a wall of darkness. Whatever was out there isn’t interested in being seen anymore.",
    sceneryDescription:
      "The screen fills most of the forward view from the chair, a huge rectangle of near-black broken only by distant pinpricks and sensor ghosts.",
    location: "BridgeCaptain",
    vocab: ["main", "viewer", "viewscreen", "screen"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MainViewerBridgeHelm",
    name: "main viewer",
    description:
      "From the helm, the main viewer is a reminder that the ship is adrift in an awful lot of empty, indifferent space.",
    sceneryDescription:
      "Trajectories, overlays, and targeting ghosts have long since faded, leaving the helm with a view that’s mostly void and bad ideas.",
    location: "BridgeHelm",
    vocab: ["main", "viewer", "viewscreen", "screen"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MainViewerBridgeTact",
    name: "main viewer",
    description:
      "From the tactical station, the main viewer shows no contacts, no alerts—just a vast emptiness where something dangerous used to be.",
    sceneryDescription:
      "This angle turns the display into a tactical blind spot: a whole lot of nothing that still somehow feels like it’s staring back.",
    location: "BridgeTact",
    vocab: ["main", "viewer", "viewscreen", "screen"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MainViewerBridgeComm",
    name: "main viewer",
    description:
      "From the comms station, the main viewer is just another silent surface ignoring the outgoing distress.",
    sceneryDescription:
      "Status lights from the comm console shimmer faintly across the base of the screen, as if the ship itself is still trying to talk to the void.",
    location: "BridgeComm",
    vocab: ["main", "viewer", "viewscreen", "screen"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MainViewerBridgeScience",
    name: "main viewer",
    description:
      "From the science station, the main viewer is an empty dataset—no anomalies, no incoming signals, just quiet space.",
    sceneryDescription:
      "Sensor reflections flicker faintly at the edges, but nothing resolves into anything you can blame for any of this.",
    location: "BridgeScience",
    vocab: ["main", "viewer", "viewscreen", "screen"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "ComputerContacts",
    name: "glowing contacts",
    description:
      "A cluster of touch-sensitive contacts glows serenely on the science console. Whatever else died with the crew, the computer is still very much awake.",
    sceneryDescription:
      "The contacts form a small constellation of light, arranged in patterns that would probably make sense to someone with specialist training and less corpse exposure.",
    location: "BridgeScience",
    vocab: ["glowing", "contacts", "buttons", "keys"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "MainComputer",
    name: "main computer",
    description:
      "This is the main computer interface: a hardened core of processors and storage that quietly orchestrated most of the ship’s functions. Now it idles in the dark, waiting for instructions that aren’t coming.",
    sceneryDescription:
      "Heavy panels and armored housings hide most of the hardware, but faint fans and relay clicks still whisper behind the metal. The machine survived its operators.",
    location: "BridgeScience",
    vocab: ["main", "computer", "core", "interface"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 500,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "HelmConsole",
    name: "helm console",
    description:
      "The helm console bristles with readouts, displays, and control surfaces. Most of it is incomprehensible, but one trajectory display shows the ship’s path veering sharply off course with no correction plotted afterward. Near the dead helmsman’s right hand, a circular red contact glows insistently.",
    sceneryDescription:
      "Graphs, vector lines, and numeric fields sprawl across the surface, frozen mid-crisis. The whole console has the air of a question nobody had time to answer.",
    location: "BridgeHelm",
    vocab: ["helm", "console", "navigation", "nav"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "HelmContacts",
    name: "contacts",
    description:
      "Smooth, touch-sensitive contacts stud the helm console. You have no idea what most of them do. One glowing red contact stands out from the rest.",
    sceneryDescription:
      "The contacts are arranged in careful clusters, each grouping meaningful to someone who didn’t sleep through advanced flight systems. The red one feels like a very bad idea that’s uncomfortably easy to touch.",
    location: "BridgeHelm",
    vocab: ["contacts", "controls", "buttons"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "RedHelmButton",
    name: "red button",
    description:
      "A glowing circular red contact with a crisp X symbol in its center. It has the vibe of a career-limiting move waiting to happen.",
    sceneryDescription:
      "The surface is perfectly smooth and faintly warm, the X etched into the glow like a warning label written in a language your legal department speaks fluently.",
    location: "BridgeHelm",
    vocab: ["red", "button", "glowing", "contact", "x"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      push: 'There’s a soft electronic buzz and a calm, synthetic voice: "Emergency stop cannot be initiated. Required shutdown authorization has not been given." The button keeps glowing, smugly unhelpful.',
    },
  },
  {
    id: "BombSchematic",
    name: "large screen",
    description:
      'A large multicolored display shows what looks like an electrical schematic. Dozens of color-coded lines crisscross the screen, but two wires in particular are called out—one annotated "c" and the other "d".',
    sceneryDescription:
      "The schematic sprawls across the screen in a rainbow snarl of virtual wiring. The highlighted lines form a subtle path through the chaos, hinting at the difference between cutting the right wire and becoming a temporary, airborne stain.",
    location: "BridgeTact",
    vocab: ["large", "screen", "display", "multicolored", "schematic"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 30,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "TactConsole",
    name: "weapons console",
    description:
      'This console is clearly dedicated to the ship’s weapons grid. Even without knowing the specifics, you spot power indicators labeled "SHIELDS" and "MAIN WEAPONS GRID." Prominent among the clusters of multicolored contacts are three obvious ones: a glowing red button, a glowing blue button, and a glowing green button.',
    sceneryDescription:
      "The console feels like a cockpit embedded in the bridge itself—compact, tightly organized, and designed for rapid decisions with catastrophic consequences for people very far away.",
    location: "BridgeTact",
    vocab: ["weapon", "weapons", "console", "tactical", "tact"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "BlueWeaponButton",
    name: "blue button",
    description:
      "A circular blue contact with a single dot printed in its center. It looks like the kind of control you press when you want something big and expensive to explode somewhere far away.",
    sceneryDescription:
      "The blue glow is clean and steady, the solitary dot almost smug. It has the self-confidence of a mechanism that has absolutely ruined someone’s day before.",
    location: "BridgeTact",
    vocab: ["blue", "button", "glowing", "contact"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      push: 'You hear a soft electronic buzz. The button flashes three times, as if to say: "You are out of toys." Nothing launches.',
    },
  },
  {
    id: "GreenWeaponButton",
    name: "green button",
    description:
      "A circular green contact with a thin ring inscribed near its edge. It feels more like a system control than a straight weapon trigger, which is somehow worse.",
    sceneryDescription:
      "The green light traces a subtle halo around the symbol, making it look like the ship itself is sitting inside a fragile circle of protection.",
    location: "BridgeTact",
    vocab: ["green", "button", "glowing", "contact"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      push: "As your finger leaves the button, a representation of the ship on a nearby display flickers. The glowing ring around it vanishes. A chill creeps up your spine as the air around your ankles suddenly feels a few degrees colder.",
    },
  },
  {
    id: "RedWeaponButton",
    name: "red weapon button",
    description:
      "A circular red contact with a sharp vertical slash in its center. It radiates a quiet sort of menace, even among all the other controls.",
    sceneryDescription:
      'The symbol is simple and aggressive, like a warning glyph in a language that mostly translates to "lawyer bait."',
    location: "BridgeTact",
    vocab: ["red", "button", "glowing", "contact"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      push: "An angry electrical crackle rips through the ship’s frame, and a bright white lance of energy flashes across the main viewer. If anything was out there, it isn’t anymore.",
    },
  },
  {
    id: "TactCorpseHolster",
    name: "holster",
    description:
      "A holster made of tough synthetic fiber, shaped to fit a sidearm. It still bears the faint impression of the weapon it used to carry.",
    sceneryDescription:
      "The holster hangs at the dead officer’s side, secured to the uniform in a way that strongly implies it was never meant to be empty.",
    location: "BridgeTact",
    vocab: ["holster"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 2,
    itemSize: 3,
    isWearable: true,
    clothingSlot: "torso",
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 1,
    contains: [],
    overrides: {
      take: "You work the holster free from the dead man’s belt. He doesn’t complain.",
    },
  },
  {
    id: "BridgeCommConsole",
    name: "communications console",
    description:
      'The communications console is a forest of contacts and indicator lights, some of which are still flashing regularly. Two automated messages appear to be transmitting on repeat: one a location beacon, the other a warning. You can’t hear the audio, but a small viewscreen scrolls the text:\n\n"To any ship receiving this message, do not attempt to board our ship. A virus of unknown origin has killed our crew and may still be transmittable. As such, this ship should be considered under quarantine and should not be boarded under any circumstances."',
    sceneryDescription:
      "Even half-dead, the comm system keeps doing its job: screaming into the void that nobody should come here. You, unfortunately, did not get that memo in time.",
    location: "BridgeComm",
    vocab: ["communications", "communication", "console", "comms"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "CaptainsDesk",
    name: "captain's desk",
    description:
      "A stately-looking stained oak desk, the kind of antique you import into a starship just to prove you can. A small flat screen is mounted on an ornate brass base, with a thin keypad in front of it. A single drawer sits in the center.",
    sceneryDescription:
      "The desk anchors the ready room with old-world gravitas, the polished wood catching the light in warm tones that don’t quite fit with all the corpses and quarantine.",
    location: "BridgeReady",
    vocab: ["captain", "captain's", "desk", "drawer"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 120,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: true,
    capacity: 5,
    contains: [],
  },
  {
    id: "DeskScreen",
    name: "small screen",
    description:
      'A small console screen mounted to the desk. When inactive it’s just a dark, reflective surface; when active, the word "LOGIN:" appears near the bottom.',
    sceneryDescription:
      "The screen is framed in brushed metal, the sort of understated hardware that usually comes bundled with nondisclosure agreements.",
    location: "BridgeReady",
    vocab: ["small", "screen", "console", "monitor"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 5,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "SmallKeypad",
    name: "small keypad",
    description:
      "An ultra-thin keypad with tiny, touch-sensitive keys. It looks like the sort of thing you use to type in authorization codes and terrible ideas.",
    sceneryDescription:
      "The keys are almost flush with the surface, more implied than visible. Whatever inputs they expect, they’re the kind that come with court-martial paperwork if you guess wrong.",
    location: "BridgeReady",
    vocab: ["small", "flat", "keyboard", "keypad"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "LogPanel",
    name: "panel",
    description:
      "A smooth panel concealed beneath the desk drawer, featuring a thin slot in its center. A black strip runs across the top of the slot.",
    sceneryDescription:
      "The panel is designed to be invisible until you know where to look. The slot is just wide enough for some kind of badge or keycard—very exclusive, very ominous.",
    location: "BridgeReady",
    vocab: ["panel"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 5,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "LogPanelSlot",
    name: "slot",
    description:
      "A thin black slot, about three inches across, set into the panel. Whatever goes in there probably decides who gets to see what.",
    sceneryDescription:
      "The slot’s matte finish makes it hard to judge depth. It has the same quiet authority as a locked door with no handle and too many cameras.",
    location: "BridgeReady",
    vocab: ["black", "slot", "badge", "reader"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 1,
    contains: [],
  },
  {
    id: "Terrarium",
    name: "terrarium",
    description:
      "A large glass terrarium stands to one side of the ready room, filled with leafy branches and greenery. Several huge, hairy spiders prowl lazily among the foliage. They look like tarantulas, and they’re very much alive. Whatever killed the Machina’s crew did exactly nothing to the Captain’s pets.",
    sceneryDescription:
      "The terrarium is built like a high-end display case, with reinforced corners and seamless panels. Shadows crawl slowly inside as the spiders move—eight-legged anxiety behind safety glass.",
    location: "BridgeReady",
    vocab: ["terrarium", "aquarium", "glass", "cage", "case"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 5,
    contains: ["Spiders"],
    overrides: {
      open: "You don’t see any obvious way to open the terrarium. Which is probably the first good news you’ve had all day.",
    },
  },
  {
    id: "Spiders",
    name: "spiders",
    description:
      "Three massive tarantulas stalk the foliage inside the terrarium. They’re dark brown, covered in bristly hairs, and each is about the size of your hand.",
    sceneryDescription:
      "They move with unnerving deliberation, pausing to test a line of silk or adjust their stance. Every so often one turns just enough that you’re sure it knows you’re watching.",
    location: "BridgeReady",
    vocab: ["spider", "spiders", "tarantula", "tarantulas"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "Gah! They’re crawling up your arm!\n\n…heh. No. They’re sealed safely inside the terrarium. You can’t get to them.",
      kiss: "You lean in, pucker up, and—Gah! A tarantula launches itself at your face!\nAAAA—\n…just kidding. You can’t get close enough; the glass does its job.",
    },
  },
  {
    id: "WarRoomTable",
    name: "conference table",
    description:
      "A large, long conference table dominates the center of the room. Ten chairs are gathered around it, some slightly askew.",
    sceneryDescription:
      "The table surface is scarred with scuffs and faint ring marks from cups and datapads. It looks like the sort of place where people have had to make ugly decisions on not enough sleep.",
    location: "LevelOneConf",
    vocab: ["conference", "table"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 150,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 10,
    contains: [],
  },
  {
    id: "WarRoomChairs",
    name: "conference chairs",
    description:
      "The conference chairs are scattered around the table, turned at odd angles. Their positions suggest the people sitting here left quickly and not by choice.",
    sceneryDescription:
      "Most of the chairs are still close to the table, but a few are spun halfway around or shoved back abruptly, like their occupants stood up mid-argument and then kept going forever.",
    location: "LevelOneConf",
    vocab: ["chair", "chairs", "conference", "seats"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "WarRoomPapers",
    name: "scattered papers",
    description:
      "Scattered across the table are hastily scrawled papers: calculations, diagrams, lists, and half-finished plans. One scribbled sheet stands out:\n\n   Virus - 40+\n   Vampires - 20+\n   Engines damaged - 5\n   Hull breached - 7\n\n   WE ARE SO SCREWED!!!\n\nThe last line is underlined several times.",
    sceneryDescription:
      "Loose sheets overlap and curl at the edges, ink smudged where someone’s hand dragged across in a hurry. The overall impression is smart people running out of both time and optimism.",
    location: "LevelOneConf",
    vocab: ["papers", "notes", "calculations", "diagrams"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "There’s no real point in carrying the papers around; they say everything you’re already worrying about.",
    },
  },
  {
    id: "WarRoomLCD",
    name: "lcd screen",
    description:
      "An LCD display above the conference table summarizes the situation in harsh, blocky text:\n\nVIRUS:\n   Origin: Alien ship, or vampires.\n   Solution: Under investigation by medical crew. Uncertain.\n   Interim: Quarantine / try to seal off Main Medical.\n\nVAMPIRES:\n   Origin: Alien ship.\n   Solution: They seem to be light intolerant.\n             They can’t see, they can only smell.\n   Interim: Keep power to the lights. Cold suits may trick them.\n\nENGINE DAMAGE:\n   Solution: Under investigation. Radiation leak limits access.\n   Interim: Try and shut them down.\n\nIMPACT / HULL BREACH:\n   Solution: Need to\n\nThe entries stop there, like the meeting ended suddenly and badly.",
    sceneryDescription:
      "White text on a dark background flickers slightly, like an exhausted mind trying to stay awake. Whoever typed this was not having a banner day.",
    location: "LevelOneConf",
    vocab: ["lcd", "screen", "display"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 15,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "ObservationWindow",
    name: "observation window",
    description:
      "You approach the curved observation window and peer out into the darkness. The outer hull of the ship stretches away from the deck, dipping low in the distance where another massive object looms. It takes you a moment to realize the object is another ship, at least as large as the Deus Ex Machina, though it doesn’t look like any design you recognize. Even in the dark you can tell its hull is pitted or honeycombed. From the angle, it appears to have collided with the Machina, the two vessels now locked together.",
    sceneryDescription:
      "The window arcs overhead in a broad curve of reinforced transparent material, framing a view that feels too big and too wrong. The other ship clings to the Machina’s hull like a tumor—full of holes, shadows, and bad intentions.",
    location: "Observation",
    vocab: ["window", "glass", "observation", "view"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "BrassRail",
    name: "brass rail",
    description:
      "A brass rail mounted on stately mahogany posts runs the entire length of the observation window’s curvature. It stands about three to four feet high, polished to a flawless shine.",
    sceneryDescription:
      "The rail gleams warmly even in the cold artificial light, a thin strip of old-world luxury separating you from a long drop and a thicker piece of glass.",
    location: "Observation",
    vocab: ["rail", "brass", "brass rail"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "Stars",
    name: "stars",
    description:
      "There must be billions and billions of them, scattered like cold fire across the black outside the dome.",
    sceneryDescription:
      "From here the stars look crisp and utterly indifferent, tiny points of light that don’t care whether this ship lives, dies, or quietly rots where it is.",
    location: "Observation",
    vocab: ["stars", "star"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "Dome",
    name: "observation dome",
    description:
      "The observation dome rises overhead, a vast hemisphere of structural glass and support struts. The peak of the dome must be sixty feet high.",
    sceneryDescription:
      "The framework forms a delicate lattice against the starfield, a reminder that between you and vacuum there’s a lot of engineering and not a lot of mercy.",
    location: "Observation",
    vocab: ["dome", "hemisphere", "observation dome"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 500,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
];
