import type { CometEntry } from "./comet-index";

export const DEFAULT_COMET_HELP_ENTRIES: CometEntry[] = [
  {
    id: "app_interface_overview",
    source: "help",
    title: "App Interface Overview",
    terms: [
      "app interface",
      "game interface",
      "game layout",
      "screen layout",
      "interface layout",
      "how is the screen laid out",
      "i dont understand the game layout",
    ],
    body: "The main interface is split into a few core areas.^^The Room Description panel sits at the top and continuously shows the current room description. The Compass sits to the right of that panel. The Log panel sits beneath the Room Description panel on the left and records commands plus game feedback. The Command Bar sits at the bottom and is where you type commands. To the right of the Log is a tabbed panel that includes Comet, Inventory, Status, Log, and Settings.",
  },
  {
    id: "room_description_panel",
    source: "help",
    title: "Room Description Panel",
    terms: [
      "room description panel",
      "room description",
      "top panel",
      "current room description",
    ],
    body: "The Room Description panel is the topmost panel. It always shows the full description of your current room.",
  },
  {
    id: "compass_panel",
    source: "help",
    title: "Compass Panel",
    terms: [
      "compass panel",
      "what does the compass do",
      "available directions",
      "compass needles",
      "direction needles",
    ],
    body: "The Compass panel sits to the right of the Room Description panel. Its needles light up to show which directions are currently available to you.",
  },
  {
    id: "compass_symbols",
    source: "help",
    title: "Compass Symbols",
    terms: [
      "four symbols around the compass",
      "compass symbols",
      "compass icons",
      "corner symbols",
      "what are the symbols around the compass",
    ],
    body: "The four symbols around the compass, starting at the upper left corner and moving clockwise, mean up, in, down, and out.",
  },
  {
    id: "compass_readout",
    source: "help",
    title: "Compass Readout",
    terms: [
      "readout beneath the compass",
      "compass readout",
      "light temp air quality",
      "audio readout",
      "noise readout",
    ],
    body: "Beneath the compass is a smaller situational readout. It reports local conditions such as light level, temperature, air quality, and audio cues. The game does not currently play sound, but the audio readout still reports notable noises.",
  },
  {
    id: "log_panel",
    source: "help",
    title: "Log Panel",
    terms: [
      "log panel",
      "main log",
      "record of commands",
      "feedback log",
      "where do messages go",
    ],
    body: "The Log panel sits beneath the Room Description panel on the left side of the screen. It records what you type and the game's responses, so you can review what happened.",
  },
  {
    id: "command_bar",
    source: "help",
    title: "Command Bar",
    terms: [
      "command bar",
      "command prompt",
      "bottom of the screen",
      "where do i type commands",
      "where do i enter commands",
    ],
    body: "The Command Bar sits at the bottom of the screen. It is the prompt where you type commands for the game.",
  },
  {
    id: "status_tabs_overview",
    source: "help",
    title: "Status Tabs Overview",
    terms: [
      "status tabs",
      "right side tabs",
      "tab panel",
      "what are the tabs",
      "what do the tabs do",
    ],
    body: "The tabbed panel to the right of the main Log contains several sections: Comet, Inventory, Status, Log, and Settings. Each tab holds a different category of information or tools.",
  },
  {
    id: "inventory_tab",
    source: "help",
    title: "Inventory",
    terms: [
      "inventory",
      "how does inventory work",
      "inventory work",
      "escher field",
      "inventory groups",
      "badges and keys",
    ],
    body: "Inventory is presented as an 'Escher field', effectively a tablet whose screen opens into a pocket dimension. It can store an unlimited number of items at no weight cost to the player.^^For organization, inventory is divided into three groups: general, badges, and keys.",
  },
  {
    id: "status_vitals",
    source: "help",
    title: "Status and Vitals",
    terms: [
      "status",
      "vitals",
      "health",
      "oxygen",
      "temperature",
      "rads",
      "eeg",
      "diagnosis",
      "what do the vitals mean",
    ],
    body: "The Status tab tracks your vitals and condition. Health measures physical injury, Oxygen tracks how much breathable air you have left, Temperature tracks body temperature, Rads shows radiation exposure, EEG is a simple brainwave readout, and DIAGNOSIS summarizes your current ailments or active effects.",
  },
  {
    id: "log_tab",
    source: "help",
    title: "Log Tab",
    terms: [
      "log tab",
      "log entries",
      "gossip",
      "gossip id",
      "read notes log",
      "where do read notes go",
    ],
    body: "The Log tab contains three subtabs: Log Entries, Gossip, and DNA.^^Log Entries store the contents of notes, books, and other readable material after you read them, and the original item is discarded so it does not clutter inventory.^^Gossip stores juicy information you learn about crew members and other figures. Each gossip item has an ID, and once learned it can sometimes be shared with NPCs.^^DNA stores samples collected with the DNA Sampler.",
  },
  {
    id: "dna_tab",
    source: "help",
    title: "DNA Tab",
    terms: [
      "dna tab",
      "dna sampler",
      "how does dna work",
      "using the dna sampler",
      "touch human remains",
    ],
    body: "Once you find the DNA Sampler, you can use it on human remains. It identifies the corpse and stores known information about that person in the DNA section of the Log tab for later reference.",
  },
  {
    id: "settings_tab",
    source: "help",
    title: "Settings",
    terms: [
      "settings",
      "settings tab",
      "crt color",
      "comet personality",
      "change the ui color",
    ],
    body: "The Settings tab lets you adjust a few interface options. CRT Color changes the default green display color to another preset, and Comet Personality changes the tone of the Comet assistant.",
  },
  {
    id: "layout_adjustment",
    source: "help",
    title: "Layout Adjustment",
    terms: [
      "dragging the borders",
      "resize layout",
      "adjust layout",
      "change panel sizes",
      "move the borders",
    ],
    body: "The layout can be adjusted by dragging the panel borders.",
  },
];
