import type { CometEntry } from "./comet-index";

export const DEFAULT_COMET_ENTRIES: CometEntry[] = [
  {
    id: "amnesia",
    terms: ["amnesia"],
    body: "A disturbance in the memory of information stored in long-term memory, in contrast to short-term memory, manifested by total or partial inability to recall past experiences. There are many varieties and potential causes of amnesia, such as Anterograde amnesia, Retrograde amnesia, Emotional/Hysterical amnesia, Lacunar amnesia, Korsakoff syndrome, Transient global amnesia, and Posthypnotic amnesia.",
  },
  {
    id: "anoxiflourine",
    terms: ["anoxiflourine"],
    body: "Anoxiflourine is an extremely powerful nervous system inhibitor, used primarily for crowd control, or as a non-lethal combat weapon. It is also often used in security systems to incapacitate would-be thieves until authorities can arrive at the scene. The drug (typically administered as a gas, or an unstable liquid concentration which quickly sublimates into a gas) is so effective, that it will shut down everything but involuntary systems for as little as a day and as long as several weeks, unless an antidote is administered.",
  },
  {
    id: "anterograde_amnesia",
    terms: ["anterograde", "amnesia"],
    body: "Anterograde amnesia is a form of amnesia where the afflicted person can not recall events after the incidence of a physical trauma.",
  },
  {
    id: "octopus",
    terms: ["octopus", "devilfish", "aquarium", "zoological", "zoo"],
    body: "The aquarium in the zoological sector on level four is home to an octopus genetically engineered to be massive in size, weighing in at an estimated 2,200 pounds, or around 1,000 kilos. Its species is a patented species called 'Magnus Polypus Rex' and has been enhanced with both massive size and long life, currently over two hundred years old",
  },
  {
    id: "aquarium",
    terms: ["aquarium", "octopus", "zoological", "zoo"],
    body: "There is a huge aquarium located in the zoological sector that contains a variety of fish, as well as a giant octopus",
  },
  {
    id: "giant_bull",
    terms: ["bull", "preserve", "grassland", "zoological", "zoo"],
    body: "The zoological sector is home to a large grassland preserve, a simulated outdoor setting inhabited by a very large bull weighing in at 1,800 pounds, or 820 kilos. Its species is a patented species called 'Dominus Taurorum' and is generally docile",
  },
  {
    id: "preserve",
    terms: ["preserve", "bull", "zoological", "zoo", "grassland"],
    body: "The preserve is in the zoological sector, and is home to a variety of animal life, including a giant bull",
  },
  {
    id: "giant_owl",
    terms: ["owl", "aviary", "zoological", "zoo", "birds"],
    body: "The zoological sector is home to a large aviary, a simulated enclosed outdoor setting inhabited by a variety of different birds, including the exhibit's crown jewel, a giant owl. Its species is a patented species called 'Regina Bubonis Ingens'. The giant owl comes out during periods of simulated night",
  },
  {
    id: "aviary",
    terms: ["aviary", "birds", "zoological", "zoo", "owl"],
    body: "The Aviary is in the zoological sector, and is home to a variety of bird life, including a giant owl. The aviary has night and day cycles",
  },
  {
    id: "artificial_intelligence",
    terms: ["AI", "artificial", "intelligence"],
    body: "Artificial Intelligence was first successfully demonstrated over 1000 years ago and has become incorporated in many aspects of modern technology, including the Central Library.",
  },
  {
    id: "aeneas",
    terms: ["aeneas", "ship", "civic", "administration"],
    body: "Aeneas is the civic designation used by many shipboard institutions, including security, identity records, public services, and navigation notices. In everyday use, residents often use Aeneas to mean the shipboard society itself rather than any single department.",
  },
  {
    id: "aeneas",
    terms: ["aeneas", "ship", "vessel"],
    body: "The Aeneas is a long-duration generation vessel built around layered civic, residential, industrial, recreational, and scientific sectors. Public-facing records usually describe it as functional rather than elegant, which is library language for 'built by committee and then made everyone live inside the committee.'",
  },
  {
    id: "central_library",
    terms: ["central library", "library", "records", "database", "archive"],
    body: "The Central Library is the shipwide indexed archive for public records, technical summaries, institutional history, and citizen-facing reference material. It is not an unrestricted security database and does not ordinarily contain private lock codes, hidden item locations, or current emergency observations unless those have been formally recorded.",
  },
  {
    id: "park_robot",
    terms: [
      "robot",
      "park",
      "vivarium",
      "trash",
      "junk",
      "garbage",
      "refuse",
      "sweepy",
    ],
    body: "A small robot known as Sweepy wanders the outdoor sections of Vivarium Park collecting loose trash in a wire bin. It is simple, dutiful, and built around the civic principle that anything in the trash robot is probably trash.",
  },
  {
    id: "gym_robot",
    terms: [
      "robot",
      "park",
      "vivarium",
      "gym",
      "weights",
      "weightlifting",
      "bro",
      "trainer",
      "spotter",
      "broseph",
      "brawn",
    ],
    body: "A robot known as 'Broseph Brawn' works as a trainer in the heavy weight section of the gymnasium 'Ultra Fitness', located in Vivarium Park. It assists visitors with their training goals and is a notoriously tough coach.",
  },
  {
    id: "bartender_robot",
    terms: [
      "robot",
      "park",
      "vivarium",
      "bar",
      "bartender",
      "barbot",
      "drinks",
      "alcohol",
      "samsynth",
      "roswink",
      "loosened tongue",
    ],
    body: "A robot known as 'Samsynth Roswink III' or sometimes 'Wink' works as a bartender at 'The Loosened Tongue', located in Vivarium Park. It mixes and serves drinks, and is also known for being a great listener, and advisor",
  },
  {
    id: "usher_robot",
    terms: [
      "robot",
      "park",
      "vivarium",
      "movie",
      "theater",
      "usher",
      "film",
      "tomothy",
    ],
    body: "A robot known as 'Tomothy Brindle' works as the usher at the movie theater 'The Cineplexperience', located in Vivarium Park. It's a film buff, obsessed with movies and is very strict about movie theater etiquette",
  },
  {
    id: "salon_robot",
    terms: [
      "robot",
      "park",
      "vivarium",
      "spa",
      "salon",
      "nails",
      "nail salon",
      "nail",
      "twizz",
      "secret",
      "keratin kindness",
    ],
    body: "A robot known as 'Twizz' works as a nail technician at the nail salon 'Keratin Kindness', part of the 'U-Deserve-U' Spa located in Vivarium Park. In addition to being an excellent nail technician, it is well known ship-wide for being an obsessive gossip hound, and that it even keeps secrets, which it will only divulge if enticed",
  },
  {
    id: "doomed_chef",
    terms: [
      "chef",
      "Matthias",
      "Venn",
      "Matthias Venn",
      "restaurant",
      "Saveurs du Passe",
      "park",
      "vivarium",
    ],
    body: "Matthias Venn is the current head chef of Saveurs du Passe, a Vivarium Park restaurant specializing in lab-grown historic and extinct-animal cuisine. The Central Library notes that high-prestige kitchens still favor human chefs for judgment, vanity, and the theatrical value of yelling at sauce.",
  },
  {
    id: "the_park",
    terms: ["park", "vivarium"],
    body: "Vivarium Park is a major recreation hub onboard the ship, and contains many amenities: An 'outdoor' park area with a simulated sky, a bar, a movie theater, a gymnasium, a restaurant, and a spa. It requires a valid park pass to enter. Its entrance is guarded by the robot Ranger Rick",
  },
  {
    id: "park_pass",
    terms: ["park pass", "pass", "vivarium pass", "park access"],
    body: "A Park Pass is the standard visitor credential for Vivarium Park. Passes may grant limited privileges for recreational areas, special events, or a fixed duration, and are normally checked by automated park staff at the entrance.",
  },
  {
    id: "park_restaurant",
    terms: [
      "restaurant",
      "Saveurs du Passe",
      "park",
      "vivarium",
      "Saveurs",
      "Passe",
      "Matthias",
      "Venn",
    ],
    body: "Saveurs du Passe is a restaurant in Vivarium Park known for comfort food, prestige dining, and lab-grown reconstructions of extinct or otherwise inadvisable ingredients. Its public listing emphasizes rustic atmosphere, historical cuisine, and the current head chef, Matthias Venn.",
  },
  {
    id: "park_movie_theater",
    terms: [
      "theater",
      "theatre",
      "movie",
      "movies",
      "film",
      "films",
      "park",
      "vivarium",
      "cineplexperience",
      "trials of fred",
    ],
    body: "The Cineplexperience is Vivarium Park's compact movie theater. It is known for rotating archival films, strict theater etiquette, and a robot usher named Tomothy Brindle who treats talking during a screening as a moral failure.",
  },
  {
    id: "park_spa",
    terms: [
      "spa",
      "park",
      "vivarium",
      "sauna",
      "steam room",
      "salon",
      "nail salon",
      "u-deserve-u",
    ],
    body: "U-Deserve-U is Vivarium Park's spa complex. Public listings describe sauna and steam facilities, beauty services, and the Keratin Kindness nail salon. The name tests well with citizens who feel underappreciated by life, management, or both.",
  },
  {
    id: "park_gymnasium",
    terms: [
      "gym",
      "park",
      "vivarium",
      "gymnasium",
      "cardio",
      "weights",
      "showers",
      "ultra fitness",
      "spin",
    ],
    body: "Ultra Fitness is a Vivarium Park gymnasium with cardio equipment, weight training areas, locker rooms, showers, and spin facilities. Its advertising leans heavily on motivational slogans and robot-assisted training, which is efficient provided one defines encouragement broadly.",
  },
  {
    id: "park_bar",
    terms: [
      "bar",
      "park",
      "vivarium",
      "pub",
      "loosened tongue",
      "drinks",
      "jukebox",
      "trivia",
    ],
    body: "The Loosened Tongue is a bar in Vivarium Park known for cocktails, bar trivia, a jukebox, and a reputation for unusually good conversation. Its current bartender is the robot Samsynth Roswink III, often called Wink.",
  },
  {
    id: "park_spa_sauna",
    terms: ["sauna", "spa", "park", "vivarium"],
    body: "Saunas are dry-heat rooms used for relaxation, circulation, and the socially sanctioned feeling of being gently cooked. U-Deserve-U lists sauna access among its standard spa amenities.",
  },
  {
    id: "park_spa_steam_room",
    terms: ["steam room", "steam", "spa", "park", "vivarium"],
    body: "Steam rooms use humid heat rather than dry heat, making them popular for relaxation, respiratory comfort, and theatrical brooding through vapor. U-Deserve-U lists steam-room access among its standard spa amenities.",
  },
  {
    id: "bar_trivia",
    terms: ["bar trivia", "trivia", "quiz", "pub quiz"],
    body: "Bar trivia is a common recreation format in which patrons answer questions for entertainment, status, or small prizes. The Central Library recommends answering from verified knowledge rather than confidence, although it concedes that confidence is usually louder.",
  },
  {
    id: "manicure_pedicure",
    terms: ["manicure", "pedicure", "mani-pedi", "mani pedi", "nails"],
    body: "A manicure is a cosmetic treatment for the hands and fingernails, while a pedicure is the equivalent service for feet and toenails. Combined appointments are often advertised as mani-pedis by establishments with limited signage space and a robust tolerance for hyphens.",
  },
  {
    id: "bufo_clutch_a",
    terms: ["bufo", "clutch", "bufo clutch", "bufo clutch a"],
    body: "Bufo Clutch A is a vast nebula located roughly midway between the Aeneas point of origin and its destination.",
  },

  {
    id: "brain_slug_holothuroidea_adduco",
    terms: ["slug", "jellyfish", "holothuroidea", "adduco"],
    body: "The Holothuroidea Adduco, or, 'Brain Slug', as it is commonly called, is one of a few xenobiological specimens collected throughut the Deus Ex Machina's journey and does indeed resemble a sort of green sea slug or jellyfish, with a bulbous gelatinous body connected to a base mass of fat, elastic tentacles. Found on the planet 'Hypnos' (so named after the Greek God of sleep, and inspired by the specimens observed there), the Brain Slug was thought at first to be an unusually large and successful non-intelligent parasite. While its nature did turn out to be parasitic, it was determined to possess the capacity for significant intelligence. Of the fifty or so other species recorded on Hypnos (examples of each stored in the zoological stasis warehouse after extensive study) examples of nearly all were found harboring a Slug. The Slug always connected on or at the base of the head, where, being acquatic by nature, the Slug was thought to connect when an unsuspecting animal came to drink. Animals so afflicted were found to be unusually successful, and they displayed what seemed to be a higher order of intelligence. After study it was found that nearly all of the Slug's gelatinous body consisted of a super high concentration of neuro fibers, and it's enitre network of tentacles had evolved to act as sensitive electrodes. The end result was that, by making a connection at the skull, the Brain Slug was able to actually 'tap into' the host creatures brain functions, and in fact take them over completely. The Slug then in effect acted as the brain for its new body for as long as the connections was useful (typically, it was observed, until the host animal became either too old, or too injured to be of further use). The extent of this unique ability was unfortunately discovered first in the Deus Ex Machina Xenobiology Lab where it gained control of a human host. It was then discovered that the creature was actually capable of even human-level intelligence, and due to its extreme cleverness and resistance, it was very difficult to remove. In the end, only the spike of neural activity associated with the drug Trixophine inticed the Slug to depart its host willingly. No other method was successful, including anesthisising the host. The Brain Slug can be found in two forms; its active state, and its dormant state. In the dormant state, the Slug discharges all of its moisture, collapsing to a quarter of its original size, and in this state appears to be dried. Although it appears dead, it will become active quickly after being submerged in water. As long as it is connected to a viable host, it seems to be able to leech enough water from it to maintain its waking state without harming the host, but it will revert to its dormant state very quickly if separated from both a host and a source of water. The Brain Slug is considered a Class Two Dangerous Creature.",
  },

  {
    id: "cooler",
    terms: ["cooler"],
    body: "Such coolers are popular amongst military groups, humanitatian groups, and tailgate party frequenters. They are capable of providing varying levels of coolness, up to and including flash-freezing.",
  },
  {
    id: "coordinant",
    terms: ["coordinant"],
    body: "A point in space.",
  },
  {
    id: "coordinant_finder",
    terms: ["coordinant", "finder"],
    body: "A coordinant pinpointer. A simple device which generally provides a useful coordinant using a preprogrammed source point.",
  },
  {
    id: "cryonic_suits",
    terms: ["space", "cold", "suit"],
    body: "Cryonic Suits, also called Cold Suits, are any airtight suit used for work with cryonics or in cryonic laboratories. They are usually rated for use in vacuums. They may or may not be rated to withstand heavy doses of radiation.",
  },
  {
    id: "cryonics",
    terms: ["cryonics"],
    body: "The technology, firmly established for the first time in the mid 20th century, of using extreme cold to arrest a living system, with the ability of later reviving that system intact.",
  },

  {
    id: "dna",
    terms: ["DNA"],
    body: "Deoxyribonucleic Acid. The building blocks of life.",
  },
  {
    id: "dna_reader_wand",
    terms: ["DNA", "reader", "wand"],
    body: "DNA readers/analyzers can be extremely useful in both the medical and law enforcement fields; consisting of a handheld wand with a sensetive bulb located at its tip, such devices are capable of reading even minute traces of DNA and cross-refrencing the genome against a centralized database.",
  },
  {
    id: "emotional_amnesia",
    terms: ["emotional", "amnesia"],
    body: "Emotional amnesia, also called hysterical amnesia, is a form of memory loss which may be brought on by a psychological trauma.",
  },

  {
    id: "hysterical_amnesia",
    terms: ["hysterical", "amnesia"],
    body: "Hysterical amnesia, also called emotional amnesia, is a form of memory loss which may be brought on by a psychological trauma.",
  },
  {
    id: "isosceles_onche",
    terms: [
      "isosceles",
      "onche",
      "water treatment",
      "supervisor",
      "awards",
      "supervisor",
    ],
    body: "Isosceles Onche is one of the most accomplished scientists in the field of Water Treatment, having won several awards in that field which include the 'Outstanding Achievement in Porous Membrane Filtration Award', the 'Skoglund Prize for Advances in Recursive Osmosis', the 'Platinum Drop', the 'Bevelheimer-Chang Decoration for Exemplary Contributions to the Field of Water Conservation', the 'Hixton Estate Science Bestowal', the 'Brillings Tiara of Scientific Achievement', the 'Curioso Medal of Discovery for her study of sublimation', as well as an eighth award, the 'Hottest Legs Trophy', which Onche insists on displaying with the rest in all marketing material, to the chagrin of her critics, and the delight of her fans. Her current occupation is Water Treatment Supervisor. She is often photographed, and even painted, with her cat Iggy.",
  },
  {
    id: "iggy_onche",
    terms: [
      "iggy",
      "onche",
      "cat",
      "pet",
      "collar",
      "pendant",
      "onyx",
      "secret",
    ],
    body: "Iggy Onche is primarily known for being the cat of Isosceles Onche, and he is frequently photographed with her wearing his signature collar, from which hangs an onyx pendant. He captured attention as he began showing up at press conferences, important video calls, and other high-profile events. His exact breed in unknown (a mutt, in essence) but he is a short-haired, black and white cat with one ragged ear, scratched in a fight. As of this writing he is nine years of age. It is rumored that the pendant he wears contains a secret, but this has not been confirmed.",
  },
  {
    id: "mox_eegler",
    terms: ["mox", "eegler", "mox eegler", "scientist"],
    body: "Mox Eegler is a high-value Aeneas citizen and long-serving scientist credited with several significant technical breakthroughs. Public records also note a recent decline from exemplary standing after repeated objections to mayoral authority and a small assortment of social infractions, which the library will summarize as 'technically colorful.'",
  },
  {
    id: "omark_boutros",
    terms: ["omark", "boutros", "omark boutros", "power supervisor"],
    body: "Omark Boutros is listed in public records as a Power Grid Supervisor with more than twenty rotations of utilities experience. His record emphasizes initiative, high standing, and a professional association with the ship's power infrastructure.",
  },
  {
    id: "henk_umboltz",
    terms: ["henk", "umboltz", "henk umboltz", "head of security"],
    body: "Henk Umboltz is listed as Head of Aeneas Security. His public record describes him as a top-tier citizen with long security experience, while the attached social-history annotations suggest that Aeneas uses a generous definition of 'minor incident.'",
  },
  {
    id: "social_score",
    terms: ["social score", "citizen score", "standing", "citizen standing"],
    body: "Aeneas public records use social scores and citizen standing to summarize civic reliability, institutional trust, and recorded infractions. The system distinguishes major and minor infractions, though the boundary between the two appears to have been negotiated by committee.",
  },
  {
    id: "water_treatment",
    terms: ["water treatment", "water", "membrane", "ozone", "reservoir"],
    body: "Water Treatment is the shipboard department responsible for purification, reservoir management, ozone processing, membrane filtration, and other systems that keep recycled water within acceptable civic and biological tolerances.",
  },
  {
    id: "power_grid",
    terms: ["power grid", "power", "utilities", "reactor", "power supervisor"],
    body: "The Power Grid is the shipwide distribution system that routes energy through major civic, residential, industrial, and recreational sectors. Public summaries distinguish grid management from reactor operations, although most residents use 'the power' for both and then complain when either one stops working.",
  },
  {
    id: "zoological_sector",
    terms: ["zoological", "zoology", "zoo", "animal", "animals"],
    body: "The Zoological Sector maintains animal habitats, xenobiological specimens, public exhibits, and related research facilities. Its public-facing areas include attractions such as the aquarium, aviary, and preserve.",
  },
  {
    id: "three_d_printing_facility",
    terms: ["3d printing", "printing facility", "printer", "controlled item"],
    body: "The 3D Printing Facility fabricates approved parts, tools, and domestic objects from authorized templates. Printing controlled items without clearance is a civic offense, mostly because an infinite supply of useful machines becomes less charming when someone prints the wrong one.",
  },
  {
    id: "insta_roids",
    terms: ["insta-roids", "insta roids", "roids", "strength drug"],
    body: "Insta-roids are a fast-acting strength-enhancement drug associated with recreational and athletic misuse. Public health guidance classifies them as risky, especially when paired with heavy lifting, poor judgment, or the phrase 'watch this.'",
  },
  {
    id: "jacovski_zhang_disease",
    terms: ["jackovsky", "zhang", "jz"],
    body: "Named for the unfortunate husband and wife medical team who first contracted it, and who, prior to their deaths, were responsible for uncovering a wealth of valuable information about the condition, this disease primarily effects the blood, causing rapid interior clotting which begins at the extremities and works its way in over the course of days to the lungs, heart and brain. It is generally treated with pentatrosin.",
  },
  {
    id: "korsakoff_syndrome",
    terms: ["korsakoff", "syndrome"],
    body: "Korsakoff syndrome is a form of memory loss which is related to alcoholism or severe alcohol abuse.",
  },
  {
    id: "lacunar_amnesia",
    terms: ["lacunar", "amnesia"],
    body: "Lacunar amnesia is a form of amnesia where a specific event can not be recalled.",
  },
  {
    id: "matter",
    terms: ["matter"],
    body: "Matter can be niether created nor destroyed.",
  },
  {
    id: "matter_transmission",
    terms: ["matter", "transmitter"],
    body: "Matter transmission involves the instantaneous conversion of matter into energy, the transmission of said energy to a remote location, then the decoding and reconstituting of energy back into matter. Matter transmission, or teleportation as it is still sometimes called, was first demonstrated in 2041, and later perfected in 2097.",
  },
  {
    id: "me",
    terms: ["me"],
    body: "I'm afraid I don't know anything about you...",
  },
  {
    id: "pentatrosin",
    terms: ["pentatrosin"],
    body: "Pentatrosin is a powerful drug used as a counteragent to Jacovski-Zhang disease and is extremely effective in the treatment of that condition. Due to it's effects of rapid platlet clearing and cell rehydration, the drug is extremely toxic to individuals not affected by J-Z.",
  },
  {
    id: "comet",
    terms: ["comet", "terminal", "library terminal"],
    body: "Comet is a portable Central Library access terminal designed for conversational reference queries. It can summarize indexed records and offer cautious local analysis, but it is not a security override, a private diary reader, or a substitute for looking under furniture.",
  },
  {
    id: "posthypnotic_amnesia",
    terms: ["posthypnotic", "amnesia"],
    body: "Posthypnotic amnesia concerns memory loss associated with post-hypnotic suggestion.",
  },
  {
    id: "quantum_folder",
    terms: ["quantum", "folder"],
    body: "First developed some forty years ago, the technology has many applications, but transporting goods turned out to be perhaps the most common. A favorite among professionals and students alike, the Black Field Folder (sometimes called a 'Heinlein's Folder' or 'Quantum Folder') is typically slim and ranges in size from a business card or badge, to a large flatscreen. The Black Field is capable of containing an almost limitless number of objects of any size and weight (provided they can fit into the field itself). Objects within the field are visible only as a floating point of light, and have no weight making such fields a very convenient way to carry and/or ship large numbers of things. Black Fields are often equipt with neural signature technology, allowing the device to anticipate with 98% accuracy the item you wish to retrieve and feeding that item back out of the field.",
  },
  {
    id: "retrograde_amnesia",
    terms: ["retrograde", "amnesia"],
    body: "Retrograde amnesia is a form of amnesia where the afflicted person can not recall events prior to the incidence of a trauma.",
  },
  {
    id: "rum",
    terms: ["rum"],
    body: "A distilled spirit made from mollasses.",
  },
  {
    id: "scotch",
    terms: ["scotch"],
    body: "A distilled spirit made from barley",
  },
  {
    id: "screecher_alien_parrot",
    terms: ["parrot", "screecher", "xenopsephotus", "wallicus"],
    body: "The Xenopsephotus Wallicus, or Screecher as it is often called, is sometimes also referred to as the 'Alien Parrot'. This is a bit of a misnomer, in that the creature is not a bird, but it does exhibit the ability to mimic human speech and repeat it back much like the parrot does. It is in fact many times better at it than the terrestrial parrot; the Screecher has been observed to repeat back rather long phrases and is capable of remembering things it has heard for weeks or even months. It does not appear to be dangerous to humans in any way, however, on a side note, it has displayed an intense interest in predating the Brain Slug.",
  },
  {
    id: "seritroxin",
    terms: ["seritroxin", "radiation", "cure"],
    body: "Seritroxin is a powerful drug used to counteract the effects of radiation exposure.",
  },
  {
    id: "sex",
    terms: ["sex"],
    body: "Well, you see, when two or more humans love each other very much, they... The Central Library goes on for quite some time delivering a lecture which is at times, even for you, quite informational...",
  },
  {
    id: "singularity_bomb",
    terms: ["singularity", "bomb"],
    body: "Few if any weapons throughout history have generated as much controversy, anger, and fear as the singularity bomb. About seven feet long and five feet wide, usually in a rough capsule configuration (the size and shape of a human coffin, author Edward Hillman once dryly observed) is capable of creating a singularity capable of capturing and swallowing nearby planets. Although never used in combat, the field tests on the (former) planet XF133 continue to capture the imagination of people worldwide. They can be activated either by a warhead, or, by a standard issue GE detonator.",
  },
  {
    id: "space",
    terms: ["space"],
    body: "Once believed to be the final frontier, space turned out to be the penultimate frontier when, in 2518, Professor Noonenbaum's advances in 'Flagella Theory' mathematically described the presence of sub-sub-atomic flagella on sub-atomic strings on membranes on dimensions on space and time.",
  },
  {
    id: "squirrel",
    terms: ["squirrel"],
    body: "A squirrel is a small rodent, typically grey and white in color, with a bushy tail. Their diet consists mainly of nuts and grains, although they are known to scavange almost any available food source when the opportunity is presented.",
  },
  {
    id: "teleportation",
    terms: ["teleportation"],
    body: "The technology of transmitting solid matter instantaneously from one point to another.",
  },
  {
    id: "teleportation_pads",
    terms: ["teleportation", "pads"],
    body: "First developed as booths over fifty years ago, the teleportation technology was eventually reduced in size to a convenient pad at floor level which can be used to transport cargo, or, by stepping on them, people instantaneously from one location to another nearby location. Although their range is somewhat limited, by strategically positioning them they have proved very effective in covering large distances quickly by hopping from one to the next. Alternately, they can be keyed in a 'round robin' fashion so that stepping back onto a pad you've just departed actually transports you to a third pad and so on, rather than sending you back to the original one. These circuits eventually lead back to the original pad and so are handy for travelling commonly used routes. Teleportation pads can be keyed to security badges or pay travel cards.",
  },
  {
    id: "security_badges",
    terms: [
      "security badge",
      "security badges",
      "badge",
      "badges",
      "access badge",
    ],
    body: "Security badges are physical or digital credentials used by Aeneas doors, scanners, and restricted services to verify access privileges. Badge requirements vary by department and clearance level, and the Central Library does not publish bypass procedures because Legal was very firm about that.",
  },
  {
    id: "tequila",
    terms: ["tequila"],
    body: "A distilled spirit made from the blue agave plant.",
  },
  {
    id: "thumb_pads",
    terms: ["thumb", "pad"],
    body: "Thumb pads are a common crude, but effective, method of security which requires a correct thumb-print match as well as DNA match.",
  },
  {
    id: "transient_global_amnesia",
    terms: ["transientglobal", "amnesia"],
    body: "Transient global amnesia is a form of memory loss associated with advanced age.",
  },
  {
    id: "trixophine",
    terms: ["trixophine"],
    body: "Trixophine is a powerful drug used to stimulate neural activity in patients who have experienced any condition which may temporarilly interrupt, slow down, or stop the synaptic flow in the brain. In subjects whose neural activity falls within normal parameters, trixophine causes extreme visual and aural hallucinations. For this reason it is also prized as a recreational drug, and is in fact sometimes used to treat chronic depression. Trixophine is typically not immediately effective after injection, and depending on the person may take upwards of ten to twenty minutes to reach its full effect.",
  },
  {
    id: "vanitrax",
    terms: ["vanitrax"],
    body: "Vanitrax is a powerful pain killer.",
  },
  {
    id: "vitaboost",
    terms: ["vitaboost"],
    body: "VitaBOOST is the marketing name for the drug Ibuproxitine which is capable of accelerating body repair in excess of 1000% for a short time.",
  },
  {
    id: "vodka",
    terms: ["vodka"],
    body: "A distilled spirit made from either potatoes, or grain such as wheat or rye.",
  },
  {
    id: "whiskey",
    terms: ["whiskey"],
    body: "A distilled spirit made from corn.",
  },
  {
    id: "xantophol",
    terms: ["xantophol"],
    body: "Xantophol is a powerful tranquilizer.",
  },
  {
    id: "xyzzy",
    terms: ["xyzzy"],
    body: "Xyzzy is a well known 'magic word' from a pioneer interactive fiction game.",
  },
];
