import type { Item } from "../../game/types/itemTypes";

export const levelFourItems: Item[] = [
  {
    id: "FIRE",
    name: "roaring flames",
    description:
      "A wall of fire is chewing through what’s left of the hydroponic foliage, sending distorted heat ripples through the air.",
    sceneryDescription:
      "The flames crawl across blackened soil and half-melted irrigation rigs, flaring brighter whenever they find something new to eat. Heat rolls off the blaze in waves, like someone left hell’s space heater on max.",
    location: "HydroponicsOne",
    vocab: ["fire", "flames", "flame"],
    itemClass: "gas",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "Don’t stick your hand in it.",
      smell:
        "Your nose hairs singe the moment you inhale. It smells like smoke, burning plants, and bad decisions.",
      listen:
        "A dull roar with a constant crackle fills the room, like the ship is quietly being barbecued.",
    },
    isRadioactive: false,
    isContagious: false,
  },
  {
    id: "HydroGreenIND",
    name: "indicator light",
    description:
      "A circular status disk is set into the wall, glowing with a soft, ghostly green light.",
    initialDescription:
      "The disk is glowing with a ghostly green light, pulsing faintly against the metal.",
    sceneryDescription:
      "The green glow washes the nearby piping and foliage in sickly color, like an exit sign that has given up on actually helping anyone exit.",
    location: "HydroponicsOne",
    vocab: ["glow", "indicator", "light", "disk"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "GasMask",
    name: "gas mask",
    description:
      "A lightweight gas mask with a flexible face seal and twin filter cartridges. Straps at the back are designed to cinch over the head.",
    initialDescription:
      "Lying over by the fertilizer is what looks like some kind of face mask, half-dusted in chemical grit.",
    sceneryDescription:
      "The mask looks recently used, the inner seal still faintly smudged where it pressed against someone’s skin. The filters carry that faint, metallic reek of air you really shouldn’t have been breathing in the first place.",
    location: "HydroponicsCellar",
    vocab: ["gas", "mask", "gasmask"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 2,
    isWearable: true,
    clothingSlot: "head",
    isReadable: false,
    isContainer: false,
    overrides: {
      wear: "You’d need to get out of the cold suit first; the hood and helmet don’t really leave room for additional fashion accessories.",
      remove:
        "You unstrap the mask and let it hang loose. The air feels thicker and a lot less trustworthy.",
    },
  },
  {
    id: "Pipes",
    name: "pipes",
    description:
      "A network of industrial pipes snakes out from the large machine, following the walls before disappearing through the ceiling.",
    sceneryDescription:
      "Thick main lines and thinner feeder pipes form a ribcage around the room, carrying whatever cocktail the hydroponics system used to feed into the sprinklers—and, if things go wrong, probably into places it really shouldn’t.",
    location: "HydroponicsCellar",
    vocab: ["pipe", "pipes", "network"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "PipeT",
    name: "pipe T-connector",
    description:
      "A heavy T-shaped connector joins the two main units of the machine to the large central pipe. An electronic gauge with an LCD display is mounted on it.",
    sceneryDescription:
      "The junction feels like the system’s throat—everything passes through here, monitored by a compact digital gauge that quietly judges the pressure situation.",
    location: "HydroponicsCellar",
    vocab: ["t", "connector", "pipe", "junction"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 3,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MasterValve",
    name: "large metal valve",
    description:
      "A large circular metal valve, roughly three feet across, is bolted to one of the bigger pipes. It looks like the kind of thing you turn when you want something important to happen, or explode.",
    initialDescription:
      "Connected to one of the large pipes is a big metal valve, its wheel bright against the stained metal around it.",
    sceneryDescription:
      "The valve’s grip is worn smooth in a few places, suggesting someone has already had a very intense conversation with it.",
    location: "HydroponicsCellar",
    vocab: ["large", "big", "metal", "master", "valve", "wheel"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MixValve",
    name: "small metal valve",
    description:
      "A smaller circular metal valve with a rubber grip, only a couple of inches across, is mounted on the main connecting pipe.",
    initialDescription:
      "Mounted on the large pipe connecting the two loading bays is a small metal valve with a rubberized handwheel.",
    sceneryDescription:
      "The little valve looks harmless, the rubber grip invitingly textured. The fact that it’s tied into a system that sprays chemicals around the room is probably fine.",
    location: "HydroponicsCellar",
    vocab: ["small", "smaller", "metal", "mix", "valve"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 5,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "Gauge",
    name: "pressure gauge",
    description:
      "A compact pressure gauge with a small LCD display is mounted near the T-connector.",
    sceneryDescription:
      "The face of the gauge glows orange against a black background, a thin needle and digital readout collaborating to tell you just how close you are to breaking something important.",
    location: "HydroponicsCellar",
    vocab: ["pressure", "gauge", "needle", "electronic", "lcd", "display"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 2,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "MACHINE",
    name: "manual sprinkler override machine",
    description:
      'A large, heavy-looking machine dominates one wall: two upright rectangular units joined at the base and connected by a broad pipe. Each housing has a bay door that hinges downward at an angle. A black LCD gauge is mounted on the connecting pipe, and stenciled across the chassis are the words: "Manual Sprinkler System Override."',
    sceneryDescription:
      "The machine looks like someone tried to build a fire suppression system and a bomb loader out of the same hardware, then called it a safety feature.",
    location: "HydroponicsCellar",
    vocab: [
      "large",
      "machine",
      "manual",
      "sprinkler",
      "override",
      "system",
      "unit",
    ],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 400,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "CylindricalOpeningOne",
    name: "large cylindrical opening",
    description:
      "A large cylindrical opening inside the left bay, about a foot in diameter and roughly three feet deep, waits to be fitted with a pressurized canister.",
    sceneryDescription:
      "The interior walls are smooth and lined with locking grooves, clearly designed to accept only a very specific shape of canister.",
    location: "HydroponicsCellar",
    vocab: ["cylindrical", "opening", "left", "one", "large"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 1,
  },
  {
    id: "CylindricalOpeningTwo",
    name: "narrow cylindrical opening",
    description:
      "A narrower cylindrical opening inside the right bay, about four inches in diameter and about three feet deep, clearly intended for a different type of canister.",
    sceneryDescription:
      "The bore here is tight and precise, ringed with smaller locking channels—this one expects a perfectly matched payload.",
    location: "HydroponicsCellar",
    vocab: ["cylindrical", "opening", "right", "two", "narrow"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 1,
  },
  {
    id: "BayOne",
    name: "left loading bay",
    description:
      "The left loading bay is built into the first upright housing of the machine. Its heavy door hinges downward at a forty-five degree angle to reveal a large cylindrical opening when open.",
    sceneryDescription:
      "Scuff marks and faint chemical stains along the bay’s lip suggest it’s seen a lot of canisters in its time, most of them probably uncomfortably pressurized.",
    location: "HydroponicsCellar",
    vocab: ["loading", "bay", "one", "left", "door"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: true,
    capacity: 1,

    overrides: {
      insert:
        "Whatever you’re trying to load doesn’t seem to seat correctly in the bay. The opening looks keyed to a very specific canister.",
      open: "You swing the bay door down at an angle, exposing the large cylindrical opening inside.",
      close:
        "You push the bay door back up until it latches with a solid, mechanical thunk.",
    },
  },
  {
    id: "BayTwo",
    name: "right loading bay",
    description:
      "The right loading bay mirrors the left, but the opening inside is narrower, clearly designed for a different canister profile.",
    sceneryDescription:
      "The right bay’s interior is cleaner, its walls showing fewer scuffs—either it saw less use, or what it dispensed was more polite about leaving residue.",
    location: "HydroponicsCellar",
    vocab: ["loading", "bay", "two", "right", "door"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: true,
    capacity: 1,

    overrides: {
      insert:
        "The canister grinds awkwardly and refuses to sit in place. This bay is keyed to something else.",
      open: "The bay door folds down at an angle, revealing a narrow cylindrical opening inside.",
      close:
        "You push the bay door back into place until the locking mechanism clicks shut.",
    },
  },
  {
    id: "AXE",
    name: "axe",
    description:
      "A rugged axe with a wedge-shaped head flaring outward at the blade. Both head and handle are made from a lightweight polymer, clearly designed for emergency use aboard a ship that mostly pretends it doesn’t need axes.",
    sceneryDescription:
      "The edge looks serviceable, if not recently sharpened. It’s the kind of tool that solves problems by reducing them to smaller, more scattered problems.",
    location: "HydroponicsCellar",
    vocab: ["axe", "ax"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 5,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "SPRINKLERS_H1",
    name: "sprinkler system",
    description:
      "Overhead, an array of tubes and large sprinkler heads is mounted along the ceiling, spidering out above the burning hydroponic beds.",
    sceneryDescription:
      "The nozzles are blackened at the tips, some of them dripping residue. The system looks like it was built to save the plants, not the people.",
    location: "HydroponicsOne",
    vocab: ["sprinkler", "sprinklers", "system", "heads"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "SPRINKLERS_H2",
    name: "sprinkler system",
    description:
      "The same run of tubes and sprinkler heads continues overhead, branching to cover the intact sections of hydroponics.",
    sceneryDescription:
      "Here, the heads are cleaner, metal still bright where the fire hasn’t touched them yet, like they’re still deciding whether they’re going to help.",
    location: "HydroponicsTwo",
    vocab: ["sprinkler", "sprinklers", "system", "heads"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "SPRINKLERS_H3",
    name: "sprinkler system",
    description:
      "The sprinkler tubing snakes across the ceiling here as well, with heads clustered above the surviving trees.",
    sceneryDescription:
      "This section looks barely used, as if the fire died down before the system got a chance to drench everything in whatever chemical cocktail it was primed with.",
    location: "HydroponicsThree",
    vocab: ["sprinkler", "sprinklers", "system", "heads"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "SMOKE",
    name: "smoke",
    description:
      "Thick black smoke churns above the burning foliage, slowly rising toward the high ceiling.",
    sceneryDescription:
      "The smoke pools and slides across the upper reaches of the room, blotting out lights and eating definition until everything above you looks like a bad idea in gas form.",
    location: "HydroponicsOne",
    vocab: ["thick", "black", "smoke"],
    itemClass: "gas",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "NutTreeSource",
    name: "walnut source",
    description:
      "One scorched tree seems to have escaped the worst of the flames. A few walnuts still cling to branches high overhead, stubborn and probably not worth the effort.",
    sceneryDescription:
      "Charred bark and browned leaves cling to life around the remaining nuts. Every intact shell looks like it’s waiting to be pried loose by someone with more optimism than sense.",
    location: "HydroponicsThree",
    vocab: ["walnut", "nut", "nuts", "tree"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "NutTree",
    name: "walnut tree",
    description:
      "The walnut tree has been scorched by the fire, its leaves curled and blackened. A few nuts still appear intact on its surviving branches.",
    sceneryDescription:
      "The trunk is charred in streaks, and most of the foliage is crisped. The remaining nuts hang on like tiny, carbon-flavored prizes.",
    location: "HydroponicsThree",
    vocab: ["tree", "walnut", "nut"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "LargeBurnedTree",
    name: "large burned tree",
    description:
      "You’re not sure what kind of tree it was. What’s left is a large trunk with spindly blackened branches jutting out from about three feet off the ground.",
    sceneryDescription:
      "The branches claw at the air like skeletal fingers, ash-flaking whenever the air stirs. Whatever it grew here once, it’s going to stay dead.",
    location: "HydroponicsThree",
    vocab: ["burned", "tree", "large"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 250,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "TallBurnedTree",
    name: "tall burned tree",
    description:
      "A tall blackened trunk rises about six feet before the remains of upward-pointing branches appear, continuing up into the darkness.",
    sceneryDescription:
      "The charred column disappears into shadow, a vertical scar etched into the artificial sky of the hydroponic bay.",
    location: "HydroponicsThree",
    vocab: ["burned", "tree", "tall"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 250,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "ZookeeperBracelet",
    name: "small metallic bracelet",
    description:
      'A small metallic bracelet engraved with the words: "DeM Department of Zoology." The metal is cold, the engraving sharp and official-looking.',
    initialDescription:
      "Around the corpse’s wrist is a small metallic bracelet that catches the light.",
    sceneryDescription:
      "The bracelet looks like a staff ID band, the sort of thing that gets you into areas full of dangerous animals and terrible insurance policies.",
    location: "OneEastBed",
    vocab: ["small", "metallic", "bracelet", "zookeeper"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: true,
    clothingSlot: "wrist",
    isReadable: true,
    readableText: "DeM Department of Zoology",
    isContainer: false,
  },
  {
    id: "ANIMALPODS",
    name: "cryopods",
    description:
      "Rows upon rows of cryogenic chambers stretch away in all directions—small, medium, large, and huge pods stacked like refrigerated filing cabinets for the galaxy’s stranger lifeforms.",
    sceneryDescription:
      "There must be thousands of sealed pods here, each one a cold, silent question about what’s sleeping inside and whether it wakes up hungry.",
    location: "ZooThree",
    vocab: [
      "cryogenic",
      "chambers",
      "small",
      "medium",
      "large",
      "huge",
      "pods",
      "cryopods",
    ],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 1000,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "JintosCryopod",
    name: "large cryopod",
    description:
      "A large cryopod designed to carry something significantly bigger than a person. The pod’s hatch is built to seal tight, and a vital signs monitor is mounted alongside it with dark, empty readouts.",
    initialDescription:
      "One cryopod in particular stands out: its vital signs monitor is dark, and the chamber is noticeably larger than the others, clearly meant to hold a massive animal.",
    sceneryDescription:
      "The padded interior looks like an oversized coffin lined for comfort. Scratches and impressions in the padding hint that something large and heavy has spent a lot of time in there.",
    location: "ZooThree",
    vocab: ["large", "cryopod", "sleep", "chamber", "pod"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 500,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: true,
    capacity: 2,
  },
  {
    id: "Transformers",
    name: "spare transformers",
    description:
      "Beyond the tangle of debris you can see rows of power transformers, some of them cracked and scorched from the explosion.",
    sceneryDescription:
      "The boxy housings are dented and blackened where shrapnel and heat hit hardest. They hum with the eerie stillness of equipment that should be buzzing but isn’t.",
    location: "RemotePowerStation",
    vocab: ["transformer", "transformers"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 300,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "You can see them through the debris, but there’s no way you’re getting to them without a demolition crew and a signed waiver.",
    },
  },
  {
    id: "Fuses",
    name: "replacement fuses",
    description:
      "Several trays of replacement fuses lie scattered beyond the twisted metal, most of them shattered by the blast.",
    sceneryDescription:
      "Glass and ceramic shards glitter faintly among the debris, like someone murdered a box of Christmas lights.",
    location: "RemotePowerStation",
    vocab: ["fuse", "fuses"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 10,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "They’re broken, out of reach, and buried in wreckage. Even if you could get to them, they’d be about as useful as a glass hammer.",
    },
  },
  {
    id: "WWires",
    name: "wire spools",
    description:
      "Spools of wire are stacked behind the debris, some of them partially uncoiled, looping out into the wreckage.",
    sceneryDescription:
      "The coiled lengths of wire look heavy and stubborn, the kind of thing that promises back problems if you ever tried to haul them out of here.",
    location: "RemotePowerStation",
    vocab: ["wire", "wires", "spools"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 150,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "Even if you could reach them through the debris—which you can’t—the spools would be too bulky to carry around.",
    },
  },
  {
    id: "FlashCELLZero",
    name: "Powergizer battery cell",
    description:
      'A black and silver cylindrical battery cell, about an inch in diameter and four inches long. The logo "Powergizer" is printed along the side in confident marketing font.',
    sceneryDescription:
      "The casing is scuffed but intact, the contact ends still clean. It looks like it still has some life left in it, unlike a lot of things on this ship.",
    location: "UNKNOWN",
    vocab: ["powergizer", "battery", "cell"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: true,
    readableText: "Powergizer",
    isContainer: false,
    remainingCharge: 50,
  },
  {
    id: "FlashCELLTwo",
    name: "Robustcell battery cell",
    description:
      'A black and gold cylindrical battery cell, about an inch in diameter and four inches long. The logo "Robustcell" is stamped along its side.',
    initialDescription:
      "Lying near the debris to the north is a small cylindrical battery, half-hidden among the wreckage.",
    sceneryDescription:
      "The gold detailing is chipped but still flashy, like a luxury brand that insists it’s better than the others right up until everything explodes.",
    location: "RemotePowerStation",
    vocab: ["robustcell", "battery", "cell"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: true,
    readableText: "Robustcell",
    isContainer: false,
    remainingCharge: 550,
  },
  {
    id: "RemoteYellowIND",
    name: "indicator light",
    description:
      "A circular status disk mounted to the wall, its surface glowing with a hard, electric yellow light.",
    initialDescription:
      "The disk is glowing with an electric yellow light that cuts sharply through the shadows.",
    sceneryDescription:
      "The yellow glow gives the surrounding bulkhead a jaundiced cast, like the whole station is running on borrowed power and bad health.",
    location: "RemotePowerStation",
    vocab: ["glow", "indicator", "light", "disk"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "GridYellowIND",
    name: "indicator light",
    description: "The disk is glowing with an electric yellow light.",
    sceneryDescription: "",
    location: "PowerGrid",
    vocab: ["glow", "indicator", "light", "disk"],
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    providesLight: true,
  },
  {
    id: "PowerStation",
    name: "power station",
    description:
      "It looks like the ship’s nervous system, all blinking indicators and quiet hums.",
    sceneryDescription:
      "A massive control station for the ship’s power grid dominates the room, a dizzying forest of gauges and lights covering its surface. The lights are a mixture of greens, yellows, and reds, and you can see that some of the gauges needles are moving into the warning zone but don't have a clear idea what they all mean.",
    location: "PowerGrid",
    vocab: ["grid", "power", "station", "console", "panel"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 0,
    },
    itemWeight: 800,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "PowerStationKeyboard",
    name: "power station keyboard",
    description: "The legends on some of the keys are half-worn away.",
    sceneryDescription:
      "In the middle of the main panel is a well-used keyboard, its keys slightly polished from long hours of nervous typing,",
    location: "PowerGrid",
    vocab: ["keyboard", "keypad"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 1,
    },
    itemWeight: 3,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },
  {
    id: "PowerStationKey",
    name: "large yellow and black key",
    description:
      "A large, heavy key with a rectangular grip striped in yellow and black hazard colors. It was clearly designed to make whoever turns it feel important and slightly terrified.",
    sceneryDescription:
      "The grip is textured and over-engineered, like someone wanted to make absolutely sure you understood that turning this thing does not count as a small decision.",
    location: "PowerGrid",
    vocab: ["large", "key", "black", "yellow", "rectangular"],
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      take: "You wrap your hand around the oversized grip. It comes free only if the system isn’t keyed on; otherwise it refuses to budge, like the hardware equivalent of a disapproving look.",
    },
  },
  {
    id: "PowerStationMonitor",
    name: "view screen",
    description:
      "The viewscreen is mounted above the power station keyboard. This must be how you access the ship's power systems.",
    sceneryDescription: `and mounted above the keyboard is a flat nineteen-inch viewscreen, where a prompt appears in the bottom corner inviting: "To log in type LOGIN".`,
    location: "PowerGrid",
    vocab: ["view", "screen", "monitor", "video", "viewscreen"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 2,
    },
    itemWeight: 10,
    itemSize: 3,
    isWearable: false,
    isReadable: false,
    isContainer: false,
  },

  {
    id: "PowerStationKeyhole",
    name: "large keyhole",
    description:
      "The receptacle seems to be for a key, presumably needed in order to activate the console.",
    sceneryDescription: `Next to the keyboard is a large, round silver receptacle, like a keyhole for a large key. Markings show two positions: one labeled "O" and one labeled "I".`,
    location: "PowerGrid",
    vocab: ["power", "keyhole", "receptacle", "slot"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 3,
    },
    itemWeight: 5,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    isOpenable: false,
    capacity: 1,

    overrides: {
      insert:
        "The large key slides into the receptacle with a heavy, mechanical click that suggests you just did something expensive.",
    },
  },
  {
    id: "PowerStationButton",
    name: "square red button",
    description:
      "Next to the keyhole there is a square, raised red button. In idle mode it’s dark; when the key is turned it flashes, and once power is fully engaged it glows with a steady, solid light.",
    sceneryDescription:
      "Next to the receptable is a square, raised red button.",
    location: "PowerGrid",
    vocab: ["square", "red", "button"],
    itemClass: "solid",
    itemCategory: "scenery",
    meta: {
      sceneryDescriptionOrder: 4,
    },
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    overrides: {
      push: "You press the button. If the station is properly keyed, the internal fans thump to life and the console wakes up with a low, rising hum. If not, nothing happens at all—which is its own kind of ominous.",
    },
  },
];
