import type { Item } from "../../game/types/itemTypes";
import { pushContainmentFieldButton } from "./creatures/abomination";

export const levelTwoBodyParts: Item[] = [
  {
    id: "manLegOne",
    name: "damaged male leg",
    location: "LevelTwoBurnedQuartersThree",
    vocab: ["male", "damaged", "leg", "male leg"],
    description:
      "The foot, calf, knee, and most of the thigh are all remarkably intact but its a ragged mess where it was blown off at the hip.",
    initialDescription:
      "Laying amidst the debris is the bare, bloodied leg of a man.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 50,
    itemSize: 6,
    isContagious: true,
    meta: { abominationLimb: true },
  },
  {
    id: "womanLegOne",
    name: "damaged female leg",
    location: "LevelTwoBurnedQuartersThree",
    vocab: ["female", "leg", "damaged", "female leg"],
    description:
      "It's really more of a foot, calf, and knee than it is a total leg.",
    initialDescription:
      "A bloodied woman's leg, torn loose above the knee lay on the floor.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 50,
    itemSize: 6,
    isContagious: true,
    meta: { abominationLimb: true },
  },
  {
    id: "womanArmOne",
    name: "mutilated female arm",
    location: "LevelTwoBurnedQuartersThree",
    vocab: ["female", "arm", "mutilated", "female arm"],
    description: "It got sheared off at the shoulder.",
    initialDescription:
      "A pale woman's arm, ripped off at the shoulder sits propped in one corner.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 50,
    itemSize: 6,
    isContagious: true,
    meta: { abominationLimb: true },
  },
  {
    id: "manLegTwo",
    name: "mangled male leg",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["male", "mangled", "leg", "male leg"],
    description:
      "The leg has most of its parts, but all of them are severely damaged.",
    initialDescription:
      "On the floor just inside the exploded wall is a man's mangled leg with a ragged stump.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 50,
    itemSize: 6,
    isContagious: true,
    meta: { abominationLimb: true },
  },
  {
    id: "womanArmTwo",
    name: "broken female arm",
    location: "LevelTwoBurnedBedThree",
    vocab: ["female", "broken", "arm", "female arm"],
    description:
      "The multiple breaks in the amputated arm give is a zig-zag appearance.",
    initialDescription:
      "A woman's arm lay on the carpet, visibly broken in several places.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 50,
    itemSize: 6,
    isContagious: true,
    meta: { abominationLimb: true },
  },
  {
    id: "manArmTwo",
    name: "tattooed male arm",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["male", "tattooed", "arm", "male arm"],
    description:
      "A tattoo of some sort is cut short by ragged, burned flesh, but you can't tell what it was.",
    initialDescription:
      "A man's arm lay in the middle of the floor, displaying part of a colorful tattoo.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 50,
    itemSize: 6,
    isContagious: true,
    meta: { abominationLimb: true },
  },
];

export const labItems: Item[] = [
  {
    id: "containmentField",
    name: "containment field",
    location: "Lab",
    vocab: ["containment", "field", "rig", "rigging", "metal"],
    description:
      "The circular platform is ringed with powerful emitters, all aimed at a singular spot above its surface.",
    sceneryDescription:
      "A large, circular metal platform occupies most of one corner of the lab, a globe of crackling energy hovering just above it.",
    describeScenery(state) {
      return state.worldState.abomination.containmentFieldOn
        ? "A large, circular metal platform occupies one corner of the lab, its surrounding emitters holding a globe of crackling energy just above the surface."
        : "A large, circular metal platform occupies one corner of the lab. Its surrounding emitters are dark and the air above it is empty.";
    },
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 6,
  },
  {
    id: "containmentFieldButton",
    name: "containment field button",
    location: "Lab",
    vocab: ["containment", "field", "button", "red", "panel"],
    description:
      "It's a flat, circular red button with the word 'FIELD' on it.",
    describe(state) {
      return state.worldState.abomination.containmentFieldOn
        ? "It's a flat, circular red button labeled 'FIELD'. It glows steadily."
        : "It's a flat, circular red button labeled 'FIELD'. It is currently dark.";
    },
    sceneryDescription:
      "A thick cable trails from the metal platform, across the room to a panel on the wall that has a single, flat, circular red button labeled 'FIELD'.",
    describeScenery(state) {
      const light = state.worldState.abomination.containmentFieldOn
        ? "glowing red"
        : "dark";
      return `A thick cable trails from the platform to a wall panel with a single ${light} button labeled 'FIELD'.`;
    },
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 6,
    isPushable: true,
    overrides: {
      push: pushContainmentFieldButton,
    },
  },
];

export const levelTwoItems: Item[] = [
  ...levelTwoBodyParts,
  ...labItems,
  {
    id: "iWantMyBurnedTV",
    name: "burned television set",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["burned", "tv", "television"],
    description:
      "A once-expensive flatscreen lies face down in the soot, its casing warped and blistered. Whatever plastic survived the heat has slumped into glossy black drips along the edges.",
    sceneryDescription:
      "The television has collapsed face down into the debris, all clean lines and consumer optimism burned away. The back panel is bubbled and cracked, and the screen has fused into a matte, obsidian sheet with spiderweb fractures buried under soot.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "iLoveTheSmellOfBurnedSofa",
    name: "burned sofa",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["burned", "sofa", "couch", "remains"],
    description:
      "What used to be a sofa is now a low, uneven mound of charcoal, warped springs, and ash. The outline is still there if you squint—a place where someone used to sit and pretend everything was fine.",
    sceneryDescription:
      "The sofa has collapsed into a heap of charred sticks and cinders. Blackened ribs of frame poke through the ash like bones, and here and there a scrap of fabric has survived as a smear of color that the fire missed by pure accident.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 60,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "grilledDog",
    name: "dog skeleton",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["dog", "skeleton", "dead", "body", "corpse", "carcass", "nugget"],
    initialDescription:
      "Lying on its back next to the burned sofa pieces is the charred skeleton of what looks to have been a medium-sized dog.",
    description:
      "The bones are scorched almost entirely black, fused in places where heat warped them together. From the size and build it was probably a medium dog—husky, maybe shepherd—now reduced to a brittle outline in the ash.",
    sceneryDescription:
      "A dog’s skeleton lies sprawled on its back beside the ruined sofa, ribs splayed and skull tilted in a permanent, empty grin. Every bone is charred to a dull black, with flakes of burned marrow dusting the ash beneath.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },

  {
    id: "burnedUpDresser",
    name: "burned dresser",
    location: "LevelTwoBurnedBedFour",
    vocab: ["burned", "burnt", "dresser"],
    initialDescription:
      "To one side of the burned bed is the charred base of what looks to have been a dresser.",
    description:
      "What’s left of the dresser is basically a wooden skeleton: the lower frame, crooked legs, and the warped shell of a bottom drawer fused half-shut by heat.",
    sceneryDescription:
      "The dresser’s upper half has vanished into memory and smoke. Only the lower portion remains, legs blackened and splintered, a bottom drawer frozen in place where molten varnish and ash glued it shut forever.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedUpKingSizedBed",
    name: "burned king-sized bed",
    location: "LevelTwoBurnedBedFour",
    vocab: ["burned", "burnt", "bed", "king", "sized"],
    description:
      "The bed is nothing but outline now: a charred frame and the skeletal grid of the box springs, twisted into a warped metal cage.",
    sceneryDescription:
      "Blackened beams mark where the frame used to be, surrounding a bed of steel coils that have buckled and knotted under the heat. It looks less like a place to sleep and more like something you’d wake up trapped inside.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedBedSprings",
    name: "bedsprings",
    location: "LevelTwoBurnedBedFour",
    vocab: ["skeleton", "bedspring", "bedsprings"],
    description:
      "Almost all of the mattress has been burned away, leaving only a lattice of metal coils tangled together in scorched loops.",
    sceneryDescription:
      "The bedsprings jut up in a nest of blackened wire, some coils snapped, others fused together. Ash clings to the metal, and the whole thing has the uneasy geometry of a rusted trap.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 35,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "blackenedBlob",
    name: "blackened blob",
    location: "LevelTwoBurnedQuartersThree",
    vocab: ["blackened", "blob", "tv", "television", "entertainment", "center"],
    description:
      "A melted mass of plastic, metal, and glass slumps against the wall—a once-proud entertainment center reduced to a single fused black blister.",
    sceneryDescription:
      "Whatever it used to be is mostly academic now. Half-melted components have collapsed together into a single blackened lump, cables and circuit boards fossilized into a glossy, lumpy shell.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedUpQueenSizedBed",
    name: "burned bed",
    location: "LevelTwoBurnedBedThree",
    vocab: ["burned", "burnt", "bed", "king", "sized"],
    description:
      "A charred frame outlines where the bed once stood, box springs exposed and blackened, like someone peeled the comfort right out of it.",
    sceneryDescription:
      "The remains of the bed are all hard edges and empty spaces: blackened rails, a grid of scorched springs, and a drift of ash where the mattress dissolved under the heat.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 75,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedBedSpringsToo",
    name: "bedsprings",
    location: "LevelTwoBurnedBedThree",
    vocab: ["skeleton", "bedspring", "bedsprings"],
    description:
      "Most of the mattress is simply gone, leaving the twisted metal guts of the bed exposed.",
    sceneryDescription:
      "Blackened coils crowd together in a warped grid. Some springs have snapped and curled inward, others have fused where the fire got too enthusiastic. Either way, it’s nothing you’d want to lie on now.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 30,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoSafe",
    name: "fireproof safe",
    location: "LevelTwoBurnedBedFour",
    vocab: ["safe", "fireproof"],
    initialDescription:
      "Lying on its side, as if knocked over by some brutal shockwave, is a heavy-looking fireproof safe.",
    description:
      "A heavy, rectangular safe lies on its side, its outer shell scorched but stubbornly intact. The front face is dominated by a thick door studded with six small electronic dials, each capped by a tiny blue-glowing indicator.",
    sceneryDescription:
      "The safe looks like it was designed to survive the end of the world and then file a complaint about it. Its surface is charred and smeared with soot, but the six digital indicators on the door still glimmer a cold, electric blue behind a cracked faceplate. Whatever sequence they’re showing feels more important than it probably wants to be.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 10,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    capacity: 20,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidSofa",
    name: "sofa",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["sofa", "couch"],
    description:
      "A floral-print sofa lurks under a thick coat of ash and soot. The pattern still peeks through in places, like bruises under dirty bandages.",
    sceneryDescription:
      "The sofa’s cushions sag in a tired slump, every surface filmed with grey. Beneath the soot you can still make out hints of cheerful flowers, now dulled to ghostly silhouettes on a ruined backdrop.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 65,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidLoveseat",
    name: "loveseat",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["loveseat"],
    description:
      "A smaller matching loveseat sits nearby, its floral pattern buried under a uniform ash-gray coat.",
    sceneryDescription:
      "The loveseat mirrors the sofa’s design—same hopeful upholstery, same ruin. Its arms and backrest are dusted in ash, with only rare flecks of original color fighting through.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 45,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidTV",
    name: "television",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["tv", "television"],
    description:
      "The television has toppled off its stand and lies on one side, screen shattered inward like a hollow eye punched out from the inside.",
    sceneryDescription:
      "Shards of safety glass cling to the frame around a void where the screen used to be. Cables spill from the back in a stiff, black tangle, frozen mid-fall by melted insulation.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidTVStand",
    name: "television stand",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["tv", "television", "stand"],
    description:
      "A low media stand, scorched along its edges but still structurally intact. The finish has bubbled and cracked under the heat.",
    sceneryDescription:
      "The stand looks heat-warped but stubbornly upright, a survivor’s silhouette against the charred wall. A thin layer of soot dulls whatever cheap veneer it used to brag about.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 35,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "roomAsh",
    name: "ash and soot",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["ash", "ashes", "soot"],
    description:
      "Everything here is filmed in a fine layer of ash and soot, softening edges and blurring details into the same dead gray.",
    sceneryDescription:
      "Ash drifts in corners and piles in quiet dunes along the floor, disturbed only by footprints and whatever the fire didn’t finish killing. Every surface has been dusted in the same dull powder, as if the entire level were a crime scene inside a crematorium.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },

  // SECONDARY CORRIDOR / CONFERENCE

  {
    id: "levelTwoConferenceRoomTable",
    name: "conference table",
    location: "LevelTwoConferenceRoom",
    vocab: ["conference", "table"],
    description:
      "A long, oblong conference table dominates the center of the room, bolted to the floor on two sturdy columns and topped with a smooth cream-colored surface. A single shoe protrudes from the shadows beneath it.",
    sceneryDescription:
      "The tabletop is a neutral corporate beige, scuffed by years of strategy meetings and bad coffee. Chairs ring the table, with one at the head in the unofficial position of power. From this angle, you can just see part of a woman’s shoe peeking out from underneath.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 120,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      lookunder:
        "You crouch and peer under the conference table. A young woman lies curled into the fetal position, her face a dull ashen gray with a faint bluish cast. Her lips are bloodless, dark speckling freckles the skin around her eyes and mouth, and her tongue bulges slightly between her teeth. One hand is half-open, fingers frozen around a small metal key that never made it to the lock it was meant for.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoConferenceShoe",
    name: "shoe",
    location: "LevelTwoConferenceRoom",
    vocab: ["shoe", "foot"],
    description:
      "A polished black dress shoe sticks out from beneath the edge of the conference table.",
    sceneryDescription:
      "The shoe is glossy, professional, and very much attached to the idea of a normal day at the office—right up until the moment everything stopped.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 2,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      examine:
        "It’s a polished black dress shoe with the foot of a young woman still inside it. Following the line of her leg draws your gaze under the conference table, where her body is curled up tight in the shadows.",
      take: "You leave the shoe exactly where it is. Some lines you don’t cross, even now.",
      smell:
        "It still smells faintly of shoe polish and human—congratulations, you’ve hit a new low on the olfactory scale.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoConferenceRoomLCD",
    name: "LCD display",
    location: "LevelTwoConferenceRoom",
    vocab: ["lcd", "screen", "display"],
    description:
      "A large, wall-mounted LCD display capable of showing slides, video, or acting as a digital whiteboard with a stylus. Right now it’s locked mid-scribble.",
    sceneryDescription:
      "The screen is frozen on a frantic set of hand-drawn diagrams and equations. A little wedge labeled “SHIP” and a nearby circle marked “X” dominate the sketch, with lines and arrows depicting some violent interaction between the two. Marginal notes in a hurried, neat hand read: 1) Field disrupted unexpectedly. 2) Field contraction/tear/dissolution caused major energy surge. 3) Intentional/accidental? 4) What was X? 5) Where is X?",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 6,
    isWearable: false,
    isReadable: true,
    readableText:
      "A little wedge labeled “SHIP” and a nearby circle marked “X”, surrounded by notes:\n1. Field disrupted unexpectedly\n2. Field contraction/tear/dissolution caused major energy surge\n3. Intentional/accidental?\n4. What was X?\n5. Where is X?",
    isContainer: false,
    doses: 0,
    isSwitchable: true,
    isOn: true,
    providesLight: true,
    isContagious: false,
    isRadioactive: false,
  },
];
