import type { Item } from "../../game/types/itemTypes";

export const levelTwoItems: Item[] = [
  {
    id: "iWantMyBurnedTV",
    name: "burned television set",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["burned", "tv", "television"],
    description:
      "A once-expensive flatscreen lies face down in the soot, its casing warped and blistered. Whatever plastic survived the heat has slumped into glossy black drips along the edges.",
    sceneryDescription:
      "The television has collapsed face down into the debris, all clean lines and consumer optimism burned away. The back panel is bubbled and cracked, and the screen has fused into a matte, obsidian sheet with spiderweb fractures buried under soot.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "iLoveTheSmellOfBurnedSofa",
    name: "burned sofa",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["burned", "sofa", "couch", "remains"],
    description:
      "What used to be a sofa is now a low, uneven mound of charcoal, warped springs, and ash. The outline is still there if you squint—a place where someone used to sit and pretend everything was fine.",
    sceneryDescription:
      "The sofa has collapsed into a heap of charred sticks and cinders. Blackened ribs of frame poke through the ash like bones, and here and there a scrap of fabric has survived as a smear of color that the fire missed by pure accident.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 60,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "grilledDog",
    name: "dog skeleton",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["dog", "skeleton", "dead", "body", "corpse", "carcass", "nugget"],
    initialDescription:
      "Lying on its back next to the burned sofa pieces is the charred skeleton of what looks to have been a medium-sized dog.",
    description:
      "The bones are scorched almost entirely black, fused in places where heat warped them together. From the size and build it was probably a medium dog—husky, maybe shepherd—now reduced to a brittle outline in the ash.",
    sceneryDescription:
      "A dog’s skeleton lies sprawled on its back beside the ruined sofa, ribs splayed and skull tilted in a permanent, empty grin. Every bone is charred to a dull black, with flakes of burned marrow dusting the ash beneath.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 20,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "dogTag",
    name: "brass dog tag",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["brass", "dog", "tag"],
    description:
      "A soot-streaked brass dog tag, edges dulled by heat but still stubbornly intact. The name stamped into the metal reads: “NUGGET.”",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: true,
    clothingSlot: "jewelry",
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      wear: "The collar it used to hang from burned away with the rest of the dog. You’d have to improvise something if you really wanted to wear it.",
      take: "You pry the tag free from the ash and bone with a soft metallic scrape. Poor Nugget. At least someone is finally carrying his name out of this room.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedUpDresser",
    name: "burned dresser",
    location: "LevelTwoBurnedBedFour",
    vocab: ["burned", "burnt", "dresser"],
    initialDescription:
      "To one side of the burned bed is the charred base of what looks to have been a dresser.",
    description:
      "What’s left of the dresser is basically a wooden skeleton: the lower frame, crooked legs, and the warped shell of a bottom drawer fused half-shut by heat.",
    sceneryDescription:
      "The dresser’s upper half has vanished into memory and smoke. Only the lower portion remains, legs blackened and splintered, a bottom drawer frozen in place where molten varnish and ash glued it shut forever.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedUpKingSizedBed",
    name: "burned king-sized bed",
    location: "LevelTwoBurnedBedFour",
    vocab: ["burned", "burnt", "bed", "king", "sized"],
    description:
      "The bed is nothing but outline now: a charred frame and the skeletal grid of the box springs, twisted into a warped metal cage.",
    sceneryDescription:
      "Blackened beams mark where the frame used to be, surrounding a bed of steel coils that have buckled and knotted under the heat. It looks less like a place to sleep and more like something you’d wake up trapped inside.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedBedSprings",
    name: "bedsprings",
    location: "LevelTwoBurnedBedFour",
    vocab: ["skeleton", "bedspring", "bedsprings"],
    description:
      "Almost all of the mattress has been burned away, leaving only a lattice of metal coils tangled together in scorched loops.",
    sceneryDescription:
      "The bedsprings jut up in a nest of blackened wire, some coils snapped, others fused together. Ash clings to the metal, and the whole thing has the uneasy geometry of a rusted trap.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 35,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "blackenedBlob",
    name: "blackened blob",
    location: "LevelTwoBurnedQuartersThree",
    vocab: ["blackened", "blob", "tv", "television", "entertainment", "center"],
    description:
      "A melted mass of plastic, metal, and glass slumps against the wall—a once-proud entertainment center reduced to a single fused black blister.",
    sceneryDescription:
      "Whatever it used to be is mostly academic now. Half-melted components have collapsed together into a single blackened lump, cables and circuit boards fossilized into a glossy, lumpy shell.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 50,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedUpQueenSizedBed",
    name: "burned bed",
    location: "LevelTwoBurnedBedThree",
    vocab: ["burned", "burnt", "bed", "king", "sized"],
    description:
      "A charred frame outlines where the bed once stood, box springs exposed and blackened, like someone peeled the comfort right out of it.",
    sceneryDescription:
      "The remains of the bed are all hard edges and empty spaces: blackened rails, a grid of scorched springs, and a drift of ash where the mattress dissolved under the heat.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 75,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "burnedBedSpringsToo",
    name: "bedsprings",
    location: "LevelTwoBurnedBedThree",
    vocab: ["skeleton", "bedspring", "bedsprings"],
    description:
      "Most of the mattress is simply gone, leaving the twisted metal guts of the bed exposed.",
    sceneryDescription:
      "Blackened coils crowd together in a warped grid. Some springs have snapped and curled inward, others have fused where the fire got too enthusiastic. Either way, it’s nothing you’d want to lie on now.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 30,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoSafe",
    name: "fireproof safe",
    location: "LevelTwoBurnedBedThree",
    vocab: ["safe", "fireproof"],
    initialDescription:
      "Lying on its side, as if knocked over by some brutal shockwave, is a heavy-looking fireproof safe.",
    description:
      "A heavy, rectangular safe lies on its side, its outer shell scorched but stubbornly intact. The front face is dominated by a thick door studded with six small electronic dials, each capped by a tiny blue-glowing indicator.",
    sceneryDescription:
      "The safe looks like it was designed to survive the end of the world and then file a complaint about it. Its surface is charred and smeared with soot, but the six digital indicators on the door still glimmer a cold, electric blue behind a cracked faceplate. Whatever sequence they’re showing feels more important than it probably wants to be.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 10,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    capacity: 20,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidSofa",
    name: "sofa",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["sofa", "couch"],
    description:
      "A floral-print sofa lurks under a thick coat of ash and soot. The pattern still peeks through in places, like bruises under dirty bandages.",
    sceneryDescription:
      "The sofa’s cushions sag in a tired slump, every surface filmed with grey. Beneath the soot you can still make out hints of cheerful flowers, now dulled to ghostly silhouettes on a ruined backdrop.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 65,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidLoveseat",
    name: "loveseat",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["loveseat"],
    description:
      "A smaller matching loveseat sits nearby, its floral pattern buried under a uniform ash-gray coat.",
    sceneryDescription:
      "The loveseat mirrors the sofa’s design—same hopeful upholstery, same ruin. Its arms and backrest are dusted in ash, with only rare flecks of original color fighting through.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 45,
    itemSize: 6,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidTV",
    name: "television",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["tv", "television"],
    description:
      "The television has toppled off its stand and lies on one side, screen shattered inward like a hollow eye punched out from the inside.",
    sceneryDescription:
      "Shards of safety glass cling to the frame around a void where the screen used to be. Cables spill from the back in a stiff, black tangle, frozen mid-fall by melted insulation.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "kidTVStand",
    name: "television stand",
    location: "LevelTwoBurnedQuartersTwo",
    vocab: ["tv", "television", "stand"],
    description:
      "A low media stand, scorched along its edges but still structurally intact. The finish has bubbled and cracked under the heat.",
    sceneryDescription:
      "The stand looks heat-warped but stubbornly upright, a survivor’s silhouette against the charred wall. A thin layer of soot dulls whatever cheap veneer it used to brag about.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 35,
    itemSize: 5,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "edsNecklace",
    name: "thin necklace",
    location: "INVENTORY",
    vocab: ["thin", "necklace"],
    description:
      "A delicate-looking silver necklace that clearly isn’t just silver. The chain survived the flames without even warping, ending in a pendant shaped like a star cradling two intertwined hearts.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: true,
    clothingSlot: "jewelry",
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      examine:
        "The metal catches the light with an almost stubborn brightness, star and twin hearts etched in crisp detail. Whatever alloy this is, it was built to outlive the people wearing it.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "ashPhrase",
    name: "phrase traced in ash",
    location: "LevelTwoBurnedQuartersOne",
    vocab: ["phrase", "words", "tracing"],
    description:
      "Someone knelt here in the ash and carefully traced a short message with their fingertip, right where the footprints stop.",
    sceneryDescription:
      "The ash has been disturbed in deliberate strokes, forming words that sit ghostlike on the floor. The nearby footprints come to a halt here, as if whoever wrote the message paused for a long time before moving on.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: true,
    readableText:
      "Looking closer, you see the footsteps from the south stop here and it looks like someone kneeled down to trace this message in the ash. What does it mean?",
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "yourFootprints",
    name: "footprints",
    location: "LevelTwoBurnedQuartersOne",
    vocab: ["foot", "prints", "footprints"],
    description:
      "A set of footprints, roughly your size, cross the ash from the southern doorway to the center of the room, pause at the traced phrase, then continue west.",
    sceneryDescription:
      "The prints are deep where the ash is thick and almost invisible where fire swept cleaner. They pace straight from the southern door to the phrase on the floor, then veer off toward the western exit with grim efficiency.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "yourFootprintsToo",
    name: "footprints (bathroom)",
    location: "LevelTwoBurnedBathOne",
    vocab: ["foot", "prints", "footprints"],
    description:
      "A single track of footprints leads out of the room to the north. There’s no matching set coming in.",
    sceneryDescription:
      "The footprints start near the center of the bathroom and head straight north, fading as the ash thins. There’s no sign of anyone entering the room, just someone leaving in a hurry.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "emptyRoomWashlet",
    name: "washlet",
    location: "LevelTwoBurnedBathOne",
    vocab: ["toilet", "washlet", "shitter", "can", "head"],
    description:
      "A standard washlet, ceramic and stubbornly mundane even after the fire. A fine layer of ash softens all its edges.",
    sceneryDescription:
      "The bowl and tank are filmed with gray, as if someone dusted the whole thing in fireplace residue. It looks functional, but you probably have bigger problems than indoor plumbing right now.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "emptyRoomSink",
    name: "sink",
    location: "LevelTwoBurnedBathOne",
    vocab: ["sink"],
    description:
      "A white porcelain sink, its surface dulled by a thin, even coat of ash.",
    sceneryDescription:
      "The porcelain has gone from clean clinical white to a muted, chalky gray. Ash has gathered along the drain and around the faucet handles in smudged crescents.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 30,
    itemSize: 3,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "emptyRoomShower",
    name: "shower",
    location: "LevelTwoBurnedBathOne",
    vocab: ["shower"],
    description:
      "A bare shower stall with no curtain, just tiled walls and a spray head dusted in gray.",
    sceneryDescription:
      "The stall feels strangely exposed—no curtain, no glass, nowhere to hide from the room behind you. A thin film of ash coats the floor and clings in streaks where water once ran.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 60,
    itemSize: 4,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "emptyRoomMirror",
    name: "mirror",
    location: "LevelTwoBurnedBathOne",
    vocab: ["mirror"],
    description:
      "A wall-mounted mirror with its surface fogged by ash and soot, turning any reflection into a haunted blur.",
    sceneryDescription:
      "The mirror holds a dim, smeared version of the room, as if reality itself is trying not to look too closely. Someone’s wiped it at least once, leaving streaks through the gray that only made things worse.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 10,
    itemSize: 2,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "seedTwo",
    name: "burned spider-like shell",
    location: "LevelTwoBurnedBathOne",
    vocab: ["spider", "shell", "spider-like", "husk", "burned"],
    initialDescription:
      "There seems to be some kind of small burned husk or something just to the side of the toilet.",
    description:
      "It’s a small metallic shell shaped vaguely like a spider or beetle, all segmented limbs and a rounded abdomen. The back has split open, exposing an olive-sized cavity smeared with greasy, burned residue.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      smell:
        "It gives off a faint musty scent under the overwhelming burn-smell, like old machine oil and overheated wiring.",
      taste:
        "You dab a fingertip in the greasy soot and taste it because of course you do. It’s salty, bitter, and aggressively wrong—like licking the inside of a burned-out engine.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "roomAsh",
    name: "ash and soot",
    location: "LevelTwoBurnedQuartersFour",
    vocab: ["ash", "ashes", "soot"],
    description:
      "Everything here is filmed in a fine layer of ash and soot, softening edges and blurring details into the same dead gray.",
    sceneryDescription:
      "Ash drifts in corners and piles in quiet dunes along the floor, disturbed only by footprints and whatever the fire didn’t finish killing. Every surface has been dusted in the same dull powder, as if the entire level were a crime scene inside a crematorium.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },

  // SECONDARY CORRIDOR / ARMORY / CONFERENCE

  {
    id: "whatIsThatFlashing",
    name: "flashing red light",
    location: "LevelTwoSecondaryCorridorTwo",
    vocab: ["flashing", "red", "light"],
    description:
      "Far up the corridor, a red light pulses on and off, painting the haze in nervous beats of color.",
    sceneryDescription:
      "The source is too far away to make out, but the effect is unmistakable: a stuttering blood-red blink that pushes through the smoke and ash, insisting that something up ahead is still very much alive and unhappy.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: true,
    providesLight: true,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "armorySign",
    name: "metal sign",
    location: "ARMORY",
    vocab: ["metal", "sign"],
    description: "A heavy metal warning sign bolted to the wall.",
    sceneryDescription:
      "The sign is scorched around the edges but the stenciled lettering is still sharp. Someone wanted there to be no ambiguity about what happens if you don’t follow the rules in here.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 5,
    itemSize: 2,
    isWearable: false,
    isReadable: true,
    readableText:
      "WARNING\nUNAUTHORIZED ACCESS PROHIBITED\nANOXIFLOURINE HAZARD",
    isContainer: false,
    doses: 0,
    overrides: {
      examine:
        "The sign reads:^  WARNING^  UNAUTHORIZED ACCESS PROHIBITED^  ANOXIFLOURINE HAZARD.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "cages",
    name: "metal cages",
    location: "ARMORY",
    vocab: ["metal", "wire", "cage", "cages"],
    description:
      "A row of metal security cages line the wall, their wire doors hanging open on squealing hinges.",
    sceneryDescription:
      "The cages look like they were meant to hold serious hardware—reinforced frames, lock housings, and bolted plates for extra security. Now all the doors hang open, swinging slightly as if they haven’t quite decided whether to close again.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 200,
    itemSize: 10,
    isWearable: false,
    isReadable: false,
    isContainer: true,
    capacity: 50,
    doses: 0,
    overrides: {
      get: "You decide against messing with the cages. If there’s a security system still awake in here, this is exactly how you’d trip it.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "amberGas",
    name: "faint amber gas",
    location: "ARMORY",
    vocab: ["faint", "amber", "gas", "anoxiflourine"],
    initialDescription:
      "A faint amber gas lingers in the air throughout the room.",
    description:
      "A thin amber haze hangs in the air, so faint it’s almost easy to pretend it’s just the lighting.",
    sceneryDescription:
      "The gas gives everything a soft golden tint, turning hard metal edges into blurred silhouettes. It smells like nothing at all, which is exactly the problem.",
    itemClass: "gas",
    itemCategory: "scenery",
    itemWeight: 0,
    itemSize: 0,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      smell:
        "You take the tiniest experimental breath. It’s utterly odorless, which is usually a bad sign when the word ‘hazard’ is involved.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: true,
    isRadioactive: false,
  },
  {
    id: "gunRack",
    name: "gun rack",
    location: "ARMORY",
    vocab: ["rack", "racks", "gun"],
    description:
      "An empty gun rack stands bolted to the wall, brackets and slots waiting for weapons that have already left the building.",
    sceneryDescription:
      "Scratches on the metal and faint outlines in the dust show where rifles and carbines used to rest. Whatever happened here, the weapons got claimed in a hurry.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 80,
    itemSize: 8,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      get: "You rest your hand on the rack, then think better of trying to reorganize the armory. If there’s any security still running, this is the kind of thing it might notice.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "ammoRack",
    name: "ammo rack",
    location: "ARMORY",
    vocab: ["rack", "racks", "ammo", "ammunition"],
    description:
      "A metal ammunition rack with slotted shelves for magazines and boxes, most of them empty.",
    sceneryDescription:
      "The ammo rack is mostly bare; only a few dust shadows and scuffs remain where boxes and magazines once sat. One shelf still shows the faint outline of a clip that almost—but not quite—made it out the door.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 60,
    itemSize: 7,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "clip",
    name: "gauss clip",
    location: "ARMORY",
    vocab: ["clip", "bullets", "magazine", "gauss"],
    initialDescription:
      "One magazine of ammunition seems to have been left behind, half in and half out of an ammunition rack.",
    description:
      "A lightweight magazine designed for a gauss pistol or something similar. You can’t see how many rounds are left, but it feels satisfyingly heavy.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 2,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      take: "You slide the clip free from the rack. Somewhere nearby, a system you can’t see notes the change and quietly updates its threat assessment.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoConferenceRoomTable",
    name: "conference table",
    location: "LevelTwoConferenceRoom",
    vocab: ["conference", "table"],
    description:
      "A long, oblong conference table dominates the center of the room, bolted to the floor on two sturdy columns and topped with a smooth cream-colored surface. A single shoe protrudes from the shadows beneath it.",
    sceneryDescription:
      "The tabletop is a neutral corporate beige, scuffed by years of strategy meetings and bad coffee. Chairs ring the table, with one at the head in the unofficial position of power. From this angle, you can just see part of a woman’s shoe peeking out from underneath.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 120,
    itemSize: 9,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      lookunder:
        "You crouch and peer under the conference table. A young woman lies curled into the fetal position, her face a dull ashen gray with a faint bluish cast. Her lips are bloodless, dark speckling freckles the skin around her eyes and mouth, and her tongue bulges slightly between her teeth. One hand is half-open, fingers frozen around a small metal key that never made it to the lock it was meant for.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoConferenceShoe",
    name: "shoe",
    location: "LevelTwoConferenceRoom",
    vocab: ["shoe", "foot"],
    description:
      "A polished black dress shoe sticks out from beneath the edge of the conference table.",
    sceneryDescription:
      "The shoe is glossy, professional, and very much attached to the idea of a normal day at the office—right up until the moment everything stopped.",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 2,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    overrides: {
      examine:
        "It’s a polished black dress shoe with the foot of a young woman still inside it. Following the line of her leg draws your gaze under the conference table, where her body is curled up tight in the shadows.",
      take: "You leave the shoe exactly where it is. Some lines you don’t cross, even now.",
      smell:
        "It still smells faintly of shoe polish and human—congratulations, you’ve hit a new low on the olfactory scale.",
    },
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "medicalKey",
    name: "small metal key",
    location: "LevelTwoConferenceRoom",
    vocab: ["small", "metal", "key"],
    initialDescription:
      "Resting in one of the woman’s half-open hands is a small metal key.",
    description:
      "A small, flat metal key, unmarked but clearly important enough for someone to die clutching it.",
    itemClass: "solid",
    itemCategory: "collectable",
    itemWeight: 1,
    itemSize: 1,
    isWearable: false,
    isReadable: false,
    isContainer: false,
    doses: 0,
    isSwitchable: false,
    isOn: false,
    providesLight: false,
    isContagious: false,
    isRadioactive: false,
  },
  {
    id: "levelTwoConferenceRoomLCD",
    name: "LCD display",
    location: "LevelTwoConferenceRoom",
    vocab: ["lcd", "screen", "display"],
    description:
      "A large, wall-mounted LCD display capable of showing slides, video, or acting as a digital whiteboard with a stylus. Right now it’s locked mid-scribble.",
    sceneryDescription:
      "The screen is frozen on a frantic set of hand-drawn diagrams and equations. A little wedge labeled “SHIP” and a nearby circle marked “X” dominate the sketch, with lines and arrows depicting some violent interaction between the two. Marginal notes in a hurried, neat hand read: 1) Field disrupted unexpectedly. 2) Field contraction/tear/dissolution caused major energy surge. 3) Intentional/accidental? 4) What was X? 5) Where is X?",
    itemClass: "solid",
    itemCategory: "scenery",
    itemWeight: 40,
    itemSize: 6,
    isWearable: false,
    isReadable: true,
    readableText:
      "A little wedge labeled “SHIP” and a nearby circle marked “X”, surrounded by notes:\n1. Field disrupted unexpectedly\n2. Field contraction/tear/dissolution caused major energy surge\n3. Intentional/accidental?\n4. What was X?\n5. Where is X?",
    isContainer: false,
    doses: 0,
    isSwitchable: true,
    isOn: true,
    providesLight: true,
    isContagious: false,
    isRadioactive: false,
  },
];
